alter table ITPEARLS_USER_SETTINGS add constraint FK_ITPEARLS_USER_SETTINGS_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table ITPEARLS_USER_SETTINGS add constraint FK_ITPEARLS_USER_SETTINGS_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID);
create unique index IDX_ITPEARLS_USER_SETTINGS_UK_USER_ID on ITPEARLS_USER_SETTINGS (USER_ID) where DELETE_TS is null ;
create index IDX_ITPEARLS_USER_SETTINGS_ON_USER on ITPEARLS_USER_SETTINGS (USER_ID);
create index IDX_ITPEARLS_USER_SETTINGS_ON_IMAGE on ITPEARLS_USER_SETTINGS (IMAGE_ID);
