create unique index IDX_ITPEARLS_CURRENCY_UK_CURRENCY_LONG_NAME on ITPEARLS_CURRENCY (CURRENCY_LONG_NAME) where DELETE_TS is null ;
create unique index IDX_ITPEARLS_CURRENCY_UK_CURRENCY_SHORT_NAME on ITPEARLS_CURRENCY (CURRENCY_SHORT_NAME) where DELETE_TS is null ;
