alter table HUNTTECH_PROJECT add constraint FK_HUNTTECH_PROJECT_ON_PROJECT_LOGO foreign key (PROJECT_LOGO_ID) references SYS_FILE(ID);
create index IDX_HUNTTECH_PROJECT_ON_PROJECT_LOGO on HUNTTECH_PROJECT (PROJECT_LOGO_ID);
