alter table HUNTTECH_EMPLOYEE add constraint FK_HUNTTECH_EMPLOYEE_ON_CURRENCY foreign key (CURRENCY_ID) references HUNTTECH_CURRENCY(ID);
create index IDX_HUNTTECH_EMPLOYEE_ON_CURRENCY on HUNTTECH_EMPLOYEE (CURRENCY_ID);
