alter table HUNTTECH_EMPLOYEE add constraint FK_HUNTTECH_EMPLOYEE_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references HUNTTECH_JOB_CANDIDATE(ID);
create index IDX_HUNTTECH_EMPLOYEE_ON_JOB_CANDIDATE on HUNTTECH_EMPLOYEE (JOB_CANDIDATE_ID);
