alter table HUNTTECH_EMPLOYEE add constraint FK_HUNTTECH_EMPLOYEE_ON_WORK_STATUS foreign key (WORK_STATUS_ID) references HUNTTECH_EMPLOYEE_WORK_STATUS(ID);
create index IDX_HUNTTECH_EMPLOYEE_ON_WORK_STATUS on HUNTTECH_EMPLOYEE (WORK_STATUS_ID);
