alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID);
create index IDX_ITPEARLS_EMPLOYEE_ON_JOB_CANDIDATE on ITPEARLS_EMPLOYEE (JOB_CANDIDATE_ID);
