alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_WORK_STATUS foreign key (WORK_STATUS_ID) references ITPEARLS_EMPLOYEE_WORK_STATUS(ID);
create index IDX_ITPEARLS_EMPLOYEE_ON_WORK_STATUS on ITPEARLS_EMPLOYEE (WORK_STATUS_ID);
