alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_CURRENCY foreign key (CURRENCY_ID) references ITPEARLS_CURRENCY(ID);
create index IDX_ITPEARLS_EMPLOYEE_ON_CURRENCY on ITPEARLS_EMPLOYEE (CURRENCY_ID);
