alter table HUNTTECH_SIGN_ICONS add constraint FK_HUNTTECH_SIGN_ICONS_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_SIGN_ICONS_ON_USER on HUNTTECH_SIGN_ICONS (USER_ID);
