alter table HUNTTECH_INTERNAL_EMAILER add column SELECTION_SYMBOL_FOR_ACTIONS integer ;
alter table HUNTTECH_INTERNAL_EMAILER add column REMOVED_FROM_RESERVE boolean ;
alter table HUNTTECH_INTERNAL_EMAILER add column SELECTED_FOR_ACTION boolean ;
