alter table ITPEARLS_SOCIAL_NETWORK_TYPE add constraint FK_ITPEARLS_SOCIAL_NETWORK_TYPE_ON_LOGO foreign key (LOGO_ID) references SYS_FILE(ID);
create index IDX_ITPEARLS_SOCIAL_NETWORK_TYPE_ON_LOGO on ITPEARLS_SOCIAL_NETWORK_TYPE (LOGO_ID);
