alter table HUNTTECH_SOCIAL_NETWORK_TYPE add constraint FK_HUNTTECH_SOCIAL_NETWORK_TYPE_ON_LOGO foreign key (LOGO_ID) references SYS_FILE(ID);
create index IDX_HUNTTECH_SOCIAL_NETWORK_TYPE_ON_LOGO on HUNTTECH_SOCIAL_NETWORK_TYPE (LOGO_ID);
