buildscript {
    ext.cubaVersion = '7.3-SNAPSHOT'
    repositories {
        maven {
            url 'https://repo.cuba-platform.com/content/groups/work'

            credentials {
                username(rootProject.hasProperty('repoUser') ? rootProject['repoUser'] : 'cuba')
                password(rootProject.hasProperty('repoPass') ? rootProject['repoPass'] : 'cuba123')
            }
        }


    }
    dependencies {
        classpath "com.haulmont.gradle:cuba-plugin:$cubaVersion"
    }
}

def modulePrefix = 'app'
def webContextName = 'hrm'
def coreContextName = "${webContextName}-core"

def globalModule = project(":${modulePrefix}-global")
def coreModule = project(":${modulePrefix}-core")
def webModule = project(":${modulePrefix}-web")
def guiModule = project(":${modulePrefix}-gui")
def webToolkitModule = project(":${modulePrefix}-web-toolkit")

def servletApi = 'javax.servlet:javax.servlet-api:3.1.0'

apply(plugin: 'cuba')

configurations.all {
    resolutionStrategy {
        // telegrambots 6.8+ pulls slf4j-api 2.x; logback 1.2.x (used by CUBA) requires SLF4J 1.7
        force 'org.slf4j:slf4j-api:1.7.36'
    }
}

cuba {
    artifact {
        group = 'com.company.hunttech'
        version = '0.441'
        isSnapshot = true
