-- begin ITPEARLS_COUNTRY
create unique index IDX_ITPEARLS_COUNTRY_UNIQ_COUNTRY_RU_NAME on ITPEARLS_COUNTRY (COUNTRY_RU_NAME) ^
create unique index IDX_ITPEARLS_COUNTRY_UNIQ_COUNTRY_EN_NAME on ITPEARLS_COUNTRY (COUNTRY_EN_NAME) ^
create unique index IDX_ITPEARLS_COUNTRY_UNIQ_PHONE_CODE on ITPEARLS_COUNTRY (PHONE_CODE) ^
create unique index IDX_ITPEARLS_COUNTRY_UNIQ_COUNTRY_SHORT_NAME on ITPEARLS_COUNTRY (COUNTRY_SHORT_NAME) ^
-- end ITPEARLS_COUNTRY
-- begin ITPEARLS_POSITION
create unique index IDX_ITPEARLS_POSITION_UNIQ_POSITION_RU_NAME on ITPEARLS_POSITION (POSITION_RU_NAME) ^
create unique index IDX_ITPEARLS_POSITION_UNIQ_POSITION_EN_NAME on ITPEARLS_POSITION (POSITION_EN_NAME) ^
-- end ITPEARLS_POSITION
-- begin ITPEARLS_PERSON
alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_POSITION_COUNTRY foreign key (POSITION_COUNTRY_ID) references ITPEARLS_COUNTRY(ID)^
alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_PERSON_POSITION foreign key (PERSON_POSITION_ID) references ITPEARLS_POSITION(ID)^
create unique index IDX_ITPEARLS_PERSON_UNIQ_SKYPE_NAME on ITPEARLS_PERSON (SKYPE_NAME) ^
create unique index IDX_ITPEARLS_PERSON_UNIQ_TELEGRAM_NAME on ITPEARLS_PERSON (TELEGRAM_NAME) ^
create unique index IDX_ITPEARLS_PERSON_UNIQ_WATSUP_NAME on ITPEARLS_PERSON (WATSUP_NAME) ^
create unique index IDX_ITPEARLS_PERSON_UNIQ_WIBER_NAME on ITPEARLS_PERSON (WIBER_NAME) ^
create index IDX_ITPEARLS_PERSON_ON_POSITION_COUNTRY on ITPEARLS_PERSON (POSITION_COUNTRY_ID)^
create index IDX_ITPEARLS_PERSON_ON_PERSON_POSITION on ITPEARLS_PERSON (PERSON_POSITION_ID)^
-- end ITPEARLS_PERSON

-- begin ITPEARLS_REGION
alter table ITPEARLS_REGION add constraint FK_ITPEARLS_REGION_ON_REGION_COUNTRY foreign key (REGION_COUNTRY_ID) references ITPEARLS_COUNTRY(ID)^
create unique index IDX_ITPEARLS_REGION_UNIQ_REGION_EN_NAME on ITPEARLS_REGION (REGION_EN_NAME) ^
create unique index IDX_ITPEARLS_REGION_UNIQ_REGION_RU_NAME on ITPEARLS_REGION (REGION_RU_NAME) ^
create unique index IDX_ITPEARLS_REGION_UNIQ_REGION_CODE on ITPEARLS_REGION (REGION_CODE) ^
create index IDX_ITPEARLS_REGION_ON_REGION_COUNTRY on ITPEARLS_REGION (REGION_COUNTRY_ID)^
-- end ITPEARLS_REGION
-- begin ITPEARLS_CITY
alter table ITPEARLS_CITY add constraint FK_ITPEARLS_CITY_ON_CITY_REGION foreign key (CITY_REGION_ID) references ITPEARLS_REGION(ID)^
create unique index IDX_ITPEARLS_CITY_UNIQ_CITY_EN_NAME on ITPEARLS_CITY (CITY_EN_NAME) ^
create unique index IDX_ITPEARLS_CITY_UNIQ_CITY_RU_NAME on ITPEARLS_CITY (CITY_RU_NAME) ^
create unique index IDX_ITPEARLS_CITY_UNIQ_CITY_PHONE_CODE on ITPEARLS_CITY (CITY_PHONE_CODE) ^
create index IDX_ITPEARLS_CITY_ON_CITY_REGION on ITPEARLS_CITY (CITY_REGION_ID)^
-- end ITPEARLS_CITY
-- begin ITPEARLS_OWNERSHUP
create unique index IDX_ITPEARLS_OWNERSHUP_UNIQ_SHORT_TYPE on ITPEARLS_OWNERSHUP (SHORT_TYPE) ^
create unique index IDX_ITPEARLS_OWNERSHUP_UNIQ_LONG_TYPE on ITPEARLS_OWNERSHUP (LONG_TYPE) ^
-- end ITPEARLS_OWNERSHUP
-- begin ITPEARLS_COMPANY
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_COMPANY_OWNERSHIP foreign key (COMPANY_OWNERSHIP_ID) references ITPEARLS_OWNERSHUP(ID)^
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMPANY_SHORT_NAME on ITPEARLS_COMPANY (COMPANY_SHORT_NAME) ^
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMPANY_EN_SHORT_NAME on ITPEARLS_COMPANY (COMPANY_EN_SHORT_NAME) ^
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMPANY_EN_NAME on ITPEARLS_COMPANY (COMPANY_EN_NAME) ^
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMANY_NAME on ITPEARLS_COMPANY (COMANY_NAME) ^
create index IDX_ITPEARLS_COMPANY_ON_COMPANY_OWNERSHIP on ITPEARLS_COMPANY (COMPANY_OWNERSHIP_ID)^
-- end ITPEARLS_COMPANY
