-- Включает персональные AI-предпочтения для новых и существующих пользователей.
-- Миграция выполняется один раз после изменения ранее утверждённого значения по умолчанию.

ALTER TABLE HUNTTECH_USER_SETTINGS
    ALTER COLUMN PREFER_PERSONAL_AI_API_SETTINGS SET DEFAULT TRUE;

UPDATE HUNTTECH_USER_SETTINGS
SET PREFER_PERSONAL_AI_API_SETTINGS = TRUE
WHERE PREFER_PERSONAL_AI_API_SETTINGS IS DISTINCT FROM TRUE;

ALTER TABLE HUNTTECH_USER_SETTINGS
    ADD COLUMN IF NOT EXISTS PREFER_PERSONAL_PROMPTS BOOLEAN NOT NULL DEFAULT TRUE;
