-- Идемпотентная CUBA-миграция для production-копий, где AI-структуры
-- частично создавались историческими SQL-скриптами или вручную.
-- Скрипт не удаляет таблицы, колонки и строки; CUBA автоматически
-- регистрирует его путь в SYS_DB_CHANGELOG после успешного выполнения.

DO $$
DECLARE
    image_column_renamed boolean := false;
BEGIN
    IF to_regclass('public.hunttech_open_position') IS NULL
       OR to_regclass('public.hunttech_user_settings') IS NULL
       OR to_regclass('public.sec_user') IS NULL
       OR to_regclass('public.sys_file') IS NULL THEN
        RAISE EXCEPTION
            'Базовая схема HRM HuntTech не инициализирована: требуются HUNTTECH_OPEN_POSITION, HUNTTECH_USER_SETTINGS, SEC_USER и SYS_FILE';
    END IF;

    ALTER TABLE HUNTTECH_OPEN_POSITION ADD COLUMN IF NOT EXISTS RAW_DESCRIPTION text;
    ALTER TABLE HUNTTECH_OPEN_POSITION ADD COLUMN IF NOT EXISTS INTERVIEW_CHECKLIST text;
    ALTER TABLE HUNTTECH_OPEN_POSITION ADD COLUMN IF NOT EXISTS SEARCH_MAP text;
    ALTER TABLE HUNTTECH_OPEN_POSITION ADD COLUMN IF NOT EXISTS INTERVIEW_PLAN text;

    CREATE TABLE IF NOT EXISTS HUNTTECH_USER_AI_CONFIGURATION (
        ID uuid NOT NULL,
        VERSION integer NOT NULL,
        CREATE_TS timestamp,
        CREATED_BY varchar(50),
        UPDATE_TS timestamp,
        UPDATED_BY varchar(50),
        DELETE_TS timestamp,
        DELETED_BY varchar(50),
        USER_ID uuid NOT NULL,
        PROVIDER_CODE varchar(64),
        API_KEY varchar(512),
        DEFAULT_MODEL_NAME varchar(128),
        IS_ACTIVE boolean DEFAULT true,
        CONSTRAINT PK_HUNTTECH_USER_AI_CONFIGURATION PRIMARY KEY (ID)
    );

    ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS USER_ID uuid;
    ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS PROVIDER_CODE varchar(64);
    ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS API_KEY varchar(512);
    ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS DEFAULT_MODEL_NAME varchar(128);
    ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS IS_ACTIVE boolean DEFAULT true;

    IF EXISTS (
        SELECT 1 FROM HUNTTECH_USER_AI_CONFIGURATION WHERE USER_ID IS NULL
    ) THEN
        RAISE EXCEPTION
            'HUNTTECH_USER_AI_CONFIGURATION содержит строки без USER_ID; владелец подключения не может быть восстановлен автоматически';
    END IF;
    ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ALTER COLUMN USER_ID SET NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE lower(conname) = 'fk_hunttech_user_ai_configuration_on_user'
           AND conrelid = 'hunttech_user_ai_configuration'::regclass
    ) THEN
        ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION
            ADD CONSTRAINT FK_HUNTTECH_USER_AI_CONFIGURATION_ON_USER
            FOREIGN KEY (USER_ID) REFERENCES SEC_USER (ID);
    END IF;
    CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_USER_AI_CONFIGURATION_USER
        ON HUNTTECH_USER_AI_CONFIGURATION (USER_ID);

    CREATE TABLE IF NOT EXISTS HUNTTECH_VACANCY_PROMPT_TEMPLATE (
        ID uuid NOT NULL,
        VERSION integer NOT NULL,
        CREATE_TS timestamp,
        CREATED_BY varchar(50),
        UPDATE_TS timestamp,
        UPDATED_BY varchar(50),
        DELETE_TS timestamp,
        DELETED_BY varchar(50),
        CODE varchar(64) NOT NULL,
        NAME varchar(255) NOT NULL,
        PROMPT_TEXT text,
        SYSTEM_CONTEXT varchar(1000),
        TEMPERATURE double precision DEFAULT 0.7,
        CONSTRAINT PK_HUNTTECH_VACANCY_PROMPT_TEMPLATE PRIMARY KEY (ID)
    );

    ALTER TABLE HUNTTECH_VACANCY_PROMPT_TEMPLATE ADD COLUMN IF NOT EXISTS CODE varchar(64);
    ALTER TABLE HUNTTECH_VACANCY_PROMPT_TEMPLATE ADD COLUMN IF NOT EXISTS NAME varchar(255);
    ALTER TABLE HUNTTECH_VACANCY_PROMPT_TEMPLATE ADD COLUMN IF NOT EXISTS PROMPT_TEXT text;
    ALTER TABLE HUNTTECH_VACANCY_PROMPT_TEMPLATE ADD COLUMN IF NOT EXISTS SYSTEM_CONTEXT varchar(1000);
    ALTER TABLE HUNTTECH_VACANCY_PROMPT_TEMPLATE ADD COLUMN IF NOT EXISTS TEMPERATURE double precision DEFAULT 0.7;

    IF EXISTS (
        SELECT 1 FROM HUNTTECH_VACANCY_PROMPT_TEMPLATE
         WHERE CODE IS NULL OR NAME IS NULL
    ) THEN
        RAISE EXCEPTION
            'HUNTTECH_VACANCY_PROMPT_TEMPLATE содержит строки без CODE или NAME; автоматическое заполнение запрещено';
    END IF;
    ALTER TABLE HUNTTECH_VACANCY_PROMPT_TEMPLATE ALTER COLUMN CODE SET NOT NULL;
    ALTER TABLE HUNTTECH_VACANCY_PROMPT_TEMPLATE ALTER COLUMN NAME SET NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS IDX_HUNTTECH_VACANCY_PROMPT_TEMPLATE_CODE
        ON HUNTTECH_VACANCY_PROMPT_TEMPLATE (CODE);

    CREATE TABLE IF NOT EXISTS HUNTTECH_USER_AI_PROFILE (
        ID uuid NOT NULL,
        VERSION integer NOT NULL,
        CREATE_TS timestamp,
        CREATED_BY varchar(50),
        UPDATE_TS timestamp,
        UPDATED_BY varchar(50),
        DELETE_TS timestamp,
        DELETED_BY varchar(50),
        USER_ID uuid NOT NULL,
        PROFILE_ENABLED boolean NOT NULL DEFAULT false,
        EXTERNAL_PROCESSING_ALLOWED boolean NOT NULL DEFAULT false,
        CONSENT_VERSION varchar(32),
        CONSENT_ACCEPTED_AT timestamp,
        PROFILE_CONFIRMED_AT timestamp,
        ABOUT_ME text,
        CURRENT_POSITION varchar(255),
        FUNCTIONAL_ROLE integer,
        SENIORITY_LEVEL integer,
        PROFESSIONAL_EXPERIENCE_YEARS integer,
        RECRUITING_EXPERIENCE_YEARS integer,
        CURRENT_RESPONSIBILITIES text,
        EDUCATION text,
        CERTIFICATIONS text,
        DOMAIN_EXPERTISE text,
        INDUSTRIES text,
        RECRUITING_SPECIALIZATIONS text,
        TARGET_ROLES text,
        CANDIDATE_LEVELS varchar(255),
        HIRING_GEOGRAPHIES text,
        DECISION_PRIORITIES text,
        CLIENT_PROJECT_CONTEXT text,
        PROFESSIONAL_GOALS text,
        PROFESSIONAL_INTERESTS text,
        DEVELOPMENT_AREAS text,
        CURRENT_PRIORITIES text,
        PREFERRED_LANGUAGE integer,
        RESPONSE_DETAIL_LEVEL integer,
        COMMUNICATION_STYLE integer,
        TERMINOLOGY_LEVEL integer,
        PREFERRED_ANSWER_STRUCTURE integer,
        CUSTOM_AI_INSTRUCTIONS text,
        COMMUNICATION_CONSTRAINTS text,
        CONSTRAINT PK_HUNTTECH_USER_AI_PROFILE PRIMARY KEY (ID)
    );

    -- Сверка каждой entity-колонки отдельно нужна для частично созданной таблицы.
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS USER_ID uuid;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS PROFILE_ENABLED boolean DEFAULT false;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS EXTERNAL_PROCESSING_ALLOWED boolean DEFAULT false;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CONSENT_VERSION varchar(32);
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CONSENT_ACCEPTED_AT timestamp;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS PROFILE_CONFIRMED_AT timestamp;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS ABOUT_ME text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CURRENT_POSITION varchar(255);
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS FUNCTIONAL_ROLE integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS SENIORITY_LEVEL integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS PROFESSIONAL_EXPERIENCE_YEARS integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS RECRUITING_EXPERIENCE_YEARS integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CURRENT_RESPONSIBILITIES text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS EDUCATION text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CERTIFICATIONS text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS DOMAIN_EXPERTISE text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS INDUSTRIES text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS RECRUITING_SPECIALIZATIONS text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS TARGET_ROLES text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CANDIDATE_LEVELS varchar(255);
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS HIRING_GEOGRAPHIES text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS DECISION_PRIORITIES text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CLIENT_PROJECT_CONTEXT text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS PROFESSIONAL_GOALS text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS PROFESSIONAL_INTERESTS text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS DEVELOPMENT_AREAS text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CURRENT_PRIORITIES text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS PREFERRED_LANGUAGE integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS RESPONSE_DETAIL_LEVEL integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS COMMUNICATION_STYLE integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS TERMINOLOGY_LEVEL integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS PREFERRED_ANSWER_STRUCTURE integer;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS CUSTOM_AI_INSTRUCTIONS text;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ADD COLUMN IF NOT EXISTS COMMUNICATION_CONSTRAINTS text;

    UPDATE HUNTTECH_USER_AI_PROFILE
       SET PROFILE_ENABLED = false
     WHERE PROFILE_ENABLED IS NULL;
    UPDATE HUNTTECH_USER_AI_PROFILE
       SET EXTERNAL_PROCESSING_ALLOWED = false
     WHERE EXTERNAL_PROCESSING_ALLOWED IS NULL;

    ALTER TABLE HUNTTECH_USER_AI_PROFILE ALTER COLUMN PROFILE_ENABLED SET DEFAULT false;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ALTER COLUMN PROFILE_ENABLED SET NOT NULL;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ALTER COLUMN EXTERNAL_PROCESSING_ALLOWED SET DEFAULT false;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ALTER COLUMN EXTERNAL_PROCESSING_ALLOWED SET NOT NULL;

    IF EXISTS (
        SELECT 1 FROM HUNTTECH_USER_AI_PROFILE WHERE USER_ID IS NULL
    ) THEN
        RAISE EXCEPTION
            'HUNTTECH_USER_AI_PROFILE содержит строки без USER_ID; владелец профиля не может быть восстановлен автоматически';
    END IF;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE ALTER COLUMN USER_ID SET NOT NULL;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE lower(conname) = 'fk_hunttech_user_ai_profile_on_user'
           AND conrelid = 'hunttech_user_ai_profile'::regclass
    ) THEN
        ALTER TABLE HUNTTECH_USER_AI_PROFILE
            ADD CONSTRAINT FK_HUNTTECH_USER_AI_PROFILE_ON_USER
            FOREIGN KEY (USER_ID) REFERENCES SEC_USER (ID);
    END IF;
    CREATE UNIQUE INDEX IF NOT EXISTS IDX_HUNTTECH_USER_AI_PROFILE_UNQ_USER
        ON HUNTTECH_USER_AI_PROFILE (USER_ID);

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE lower(conname) = 'chk_hunttech_user_ai_profile_prof_exp'
           AND conrelid = 'hunttech_user_ai_profile'::regclass
    ) THEN
        ALTER TABLE HUNTTECH_USER_AI_PROFILE
            ADD CONSTRAINT CHK_HUNTTECH_USER_AI_PROFILE_PROF_EXP
            CHECK (PROFESSIONAL_EXPERIENCE_YEARS IS NULL
                OR PROFESSIONAL_EXPERIENCE_YEARS BETWEEN 0 AND 70);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE lower(conname) = 'chk_hunttech_user_ai_profile_recr_exp'
           AND conrelid = 'hunttech_user_ai_profile'::regclass
    ) THEN
        ALTER TABLE HUNTTECH_USER_AI_PROFILE
            ADD CONSTRAINT CHK_HUNTTECH_USER_AI_PROFILE_RECR_EXP
            CHECK (RECRUITING_EXPERIENCE_YEARS IS NULL
                OR RECRUITING_EXPERIENCE_YEARS BETWEEN 0 AND 70);
    END IF;

    ALTER TABLE HUNTTECH_USER_SETTINGS
        ADD COLUMN IF NOT EXISTS PREFER_PERSONAL_AI_API_SETTINGS boolean DEFAULT true;
    ALTER TABLE HUNTTECH_USER_SETTINGS
        ADD COLUMN IF NOT EXISTS PREFER_PERSONAL_PROMPTS boolean DEFAULT true;

    UPDATE HUNTTECH_USER_SETTINGS
       SET PREFER_PERSONAL_AI_API_SETTINGS = true
     WHERE PREFER_PERSONAL_AI_API_SETTINGS IS NULL;
    UPDATE HUNTTECH_USER_SETTINGS
       SET PREFER_PERSONAL_PROMPTS = true
     WHERE PREFER_PERSONAL_PROMPTS IS NULL;

    ALTER TABLE HUNTTECH_USER_SETTINGS
        ALTER COLUMN PREFER_PERSONAL_AI_API_SETTINGS SET DEFAULT true;
    ALTER TABLE HUNTTECH_USER_SETTINGS
        ALTER COLUMN PREFER_PERSONAL_AI_API_SETTINGS SET NOT NULL;
    ALTER TABLE HUNTTECH_USER_SETTINGS
        ALTER COLUMN PREFER_PERSONAL_PROMPTS SET DEFAULT true;
    ALTER TABLE HUNTTECH_USER_SETTINGS
        ALTER COLUMN PREFER_PERSONAL_PROMPTS SET NOT NULL;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name = 'hunttech_user_settings'
           AND column_name = 'image_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name = 'hunttech_user_settings'
           AND column_name = 'file_image_face'
    ) THEN
        ALTER TABLE HUNTTECH_USER_SETTINGS RENAME COLUMN IMAGE_ID TO FILE_IMAGE_FACE;
        image_column_renamed := true;
    ELSIF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name = 'hunttech_user_settings'
           AND column_name = 'image_id'
    ) AND EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public'
           AND table_name = 'hunttech_user_settings'
           AND column_name = 'file_image_face'
    ) THEN
        UPDATE HUNTTECH_USER_SETTINGS
           SET FILE_IMAGE_FACE = IMAGE_ID
         WHERE FILE_IMAGE_FACE IS NULL
           AND IMAGE_ID IS NOT NULL;
    ELSE
        ALTER TABLE HUNTTECH_USER_SETTINGS ADD COLUMN IF NOT EXISTS FILE_IMAGE_FACE uuid;
    END IF;

    IF image_column_renamed
       AND EXISTS (
            SELECT 1 FROM pg_constraint
             WHERE lower(conname) = 'fk_hunttech_user_settings_on_image'
               AND conrelid = 'hunttech_user_settings'::regclass
       )
       AND NOT EXISTS (
            SELECT 1 FROM pg_constraint
             WHERE lower(conname) = 'fk_hunttech_user_settings_on_file_image_face'
               AND conrelid = 'hunttech_user_settings'::regclass
       ) THEN
        ALTER TABLE HUNTTECH_USER_SETTINGS
            RENAME CONSTRAINT FK_HUNTTECH_USER_SETTINGS_ON_IMAGE
            TO FK_HUNTTECH_USER_SETTINGS_ON_FILE_IMAGE_FACE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE lower(conname) = 'fk_hunttech_user_settings_on_file_image_face'
           AND conrelid = 'hunttech_user_settings'::regclass
    ) THEN
        ALTER TABLE HUNTTECH_USER_SETTINGS
            ADD CONSTRAINT FK_HUNTTECH_USER_SETTINGS_ON_FILE_IMAGE_FACE
            FOREIGN KEY (FILE_IMAGE_FACE) REFERENCES SYS_FILE (ID);
    END IF;

    IF image_column_renamed
       AND to_regclass('public.idx_hunttech_user_settings_on_image') IS NOT NULL
       AND to_regclass('public.idx_hunttech_user_settings_on_file_image_face') IS NULL THEN
        ALTER INDEX IDX_HUNTTECH_USER_SETTINGS_ON_IMAGE
            RENAME TO IDX_HUNTTECH_USER_SETTINGS_ON_FILE_IMAGE_FACE;
    END IF;

    CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_USER_SETTINGS_ON_FILE_IMAGE_FACE
        ON HUNTTECH_USER_SETTINGS (FILE_IMAGE_FACE);
END
$$;
^
