-- 260823-1-addGeoBlobImageFields.sql
-- Добавление BLOB полей для хранения флагов и гербов в БД (для миграции без файлового хранилища)

-- HUNTTECH_COUNTRY
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS FLAG_IMAGE BYTEA;
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS FLAG_URL VARCHAR(500);
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS COUNTRY_ENG_NAME VARCHAR(100);
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS ALPHA3_CODE VARCHAR(3);
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS NUMERIC_CODE VARCHAR(3);
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS CURRENCY_CODE VARCHAR(3);
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS CAPITAL VARCHAR(100);

-- HUNTTECH_REGION
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS EMBLEM_IMAGE BYTEA;
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS EMBLEM_URL VARCHAR(500);
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS ISO_CODE VARCHAR(10);
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS FIAS_ID VARCHAR(50);
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS REGION_TYPE VARCHAR(50);
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS CAPITAL VARCHAR(100);
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS TIME_ZONE VARCHAR(50);

-- HUNTTECH_CITY
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS EMBLEM_IMAGE BYTEA;
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS EMBLEM_URL VARCHAR(500);
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS CITY_ENG_NAME VARCHAR(100);
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS POSTAL_CODE VARCHAR(20);
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS FIAS_ID VARCHAR(50);
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS POPULATION BIGINT;
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS LATITUDE DOUBLE PRECISION;
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS LONGITUDE DOUBLE PRECISION;
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS TIME_ZONE VARCHAR(50);

-- Комментарии для документации схемы
COMMENT ON COLUMN HUNTTECH_COUNTRY.FLAG_IMAGE IS 'Флаг страны в байтах (BLOB) — хранится в БД для упрощения миграций';
COMMENT ON COLUMN HUNTTECH_COUNTRY.FLAG_URL IS 'Исходный URL флага для повторной загрузки';
COMMENT ON COLUMN HUNTTECH_REGION.EMBLEM_IMAGE IS 'Герб региона в байтах (BLOB)';
COMMENT ON COLUMN HUNTTECH_REGION.EMBLEM_URL IS 'Исходный URL герба региона';
COMMENT ON COLUMN HUNTTECH_CITY.EMBLEM_IMAGE IS 'Герб города в байтах (BLOB)';
COMMENT ON COLUMN HUNTTECH_CITY.EMBLEM_URL IS 'Исходный URL герба города';