-- Добавление полей Geo-API в HUNTTECH_USER_SETTINGS
-- Идемпотентно для CUBA updateDb

ALTER TABLE HUNTTECH_USER_SETTINGS ADD COLUMN IF NOT EXISTS GEO_API_KEY VARCHAR(255);
ALTER TABLE HUNTTECH_USER_SETTINGS ADD COLUMN IF NOT EXISTS GEO_API_SECRET VARCHAR(255);
ALTER TABLE HUNTTECH_USER_SETTINGS ADD COLUMN IF NOT EXISTS GEO_API_URL VARCHAR(255);
ALTER TABLE HUNTTECH_USER_SETTINGS ADD COLUMN IF NOT EXISTS GEO_AUTO_FETCH_FLAGS BOOLEAN DEFAULT true;
