-- Create HUNTTECH_CANDIDATE_SKILL table
CREATE TABLE IF NOT EXISTS HUNTTECH_CANDIDATE_SKILL (
    ID uuid PRIMARY KEY,
    VERSION integer NOT NULL,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    CANDIDATE_ID uuid NOT NULL,
    SKILL_ID uuid NOT NULL,
    PRIORITY integer
);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_CANDIDATE_SKILL_CANDIDATE
    ON HUNTTECH_CANDIDATE_SKILL (CANDIDATE_ID);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_CANDIDATE_SKILL_SKILL
    ON HUNTTECH_CANDIDATE_SKILL (SKILL_ID);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_HUNTTECH_CANDIDATE_SKILL_UNQ
    ON HUNTTECH_CANDIDATE_SKILL (CANDIDATE_ID, SKILL_ID)
    WHERE DELETE_TS IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_HUNTTECH_CANDIDATE_SKILL_CANDIDATE'
    ) THEN
        ALTER TABLE HUNTTECH_CANDIDATE_SKILL
            ADD CONSTRAINT FK_HUNTTECH_CANDIDATE_SKILL_CANDIDATE
            FOREIGN KEY (CANDIDATE_ID) REFERENCES HUNTTECH_JOB_CANDIDATE(ID);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_HUNTTECH_CANDIDATE_SKILL_SKILL'
    ) THEN
        ALTER TABLE HUNTTECH_CANDIDATE_SKILL
            ADD CONSTRAINT FK_HUNTTECH_CANDIDATE_SKILL_SKILL
            FOREIGN KEY (SKILL_ID) REFERENCES HUNTTECH_SKILL_TREE(ID);
    END IF;
END $$;
