-- 260823-1-addGeoBlobImageFields.sql
-- Добавление BLOB полей для хранения флагов и гербов в БД (для миграции без файлового хранилища)

-- HUNTTECH_COUNTRY
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS FLAG_IMAGE BYTEA;
ALTER TABLE HUNTTECH_COUNTRY ADD COLUMN IF NOT EXISTS FLAG_URL VARCHAR(500);

-- HUNTTECH_REGION
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS EMBLEM_IMAGE BYTEA;
ALTER TABLE HUNTTECH_REGION ADD COLUMN IF NOT EXISTS EMBLEM_URL VARCHAR(500);

-- HUNTTECH_CITY
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS EMBLEM_IMAGE BYTEA;
ALTER TABLE HUNTTECH_CITY ADD COLUMN IF NOT EXISTS EMBLEM_URL VARCHAR(500);

-- Комментарии для документации схемы
COMMENT ON COLUMN HUNTTECH_COUNTRY.FLAG_IMAGE IS 'Флаг страны в байтах (BLOB) — хранится в БД для упрощения миграций';
COMMENT ON COLUMN HUNTTECH_COUNTRY.FLAG_URL IS 'Исходный URL флага для повторной загрузки';
COMMENT ON COLUMN HUNTTECH_REGION.EMBLEM_IMAGE IS 'Герб региона в байтах (BLOB)';
COMMENT ON COLUMN HUNTTECH_REGION.EMBLEM_URL IS 'Исходный URL герба региона';
COMMENT ON COLUMN HUNTTECH_CITY.EMBLEM_IMAGE IS 'Герб города в байтах (BLOB)';
COMMENT ON COLUMN HUNTTECH_CITY.EMBLEM_URL IS 'Исходный URL герба города';