-- Добавление реквизитов и контактных данных компании (Company)
-- Идемпотентно для CUBA updateDb

ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS LEGAL_ENTITY_NAME VARCHAR(255);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS INN VARCHAR(12);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS KPP VARCHAR(9);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS OGRN VARCHAR(15);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS OKPO VARCHAR(10);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS OKTMO VARCHAR(11);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS OKVED VARCHAR(100);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS LEGAL_ADDRESS TEXT;
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS ACTUAL_ADDRESS TEXT;
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS POSTAL_ADDRESS TEXT;
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS BIK VARCHAR(9);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS BANK_NAME VARCHAR(255);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS SETTLEMENT_ACCOUNT VARCHAR(20);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS CORRESPONDENT_ACCOUNT VARCHAR(20);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS PHONE VARCHAR(50);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(100);
ALTER TABLE HUNTTECH_COMPANY ADD COLUMN IF NOT EXISTS WEBSITE VARCHAR(255);
