-- Create HUNTTECH_AI_CALL_LOG table
CREATE TABLE IF NOT EXISTS HUNTTECH_AI_CALL_LOG (
    ID uuid PRIMARY KEY,
    VERSION integer NOT NULL,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    USER_ID uuid,
    USER_LOGIN varchar(128),
    USER_NAME varchar(255),
    CALL_TIME timestamp,
    DURATION_MS bigint,
    FUNCTION_CODE varchar(64),
    FUNCTION_NAME varchar(255),
    CAPABILITY varchar(32),
    PROVIDER_CODE varchar(32),
    MODEL_NAME varchar(128),
    CREDENTIAL_OWNER varchar(32),
    PROMPT_TOKENS integer,
    COMPLETION_TOKENS integer,
    TOTAL_TOKENS integer,
    ESTIMATED_COST decimal(19, 6),
    CURRENCY varchar(8),
    PROMPT_TEXT text,
    RESPONSE_TEXT text,
    CALLER_SOURCE varchar(255),
    STATUS varchar(32),
    ERROR_MESSAGE text
);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_AI_CALL_LOG_USER
    ON HUNTTECH_AI_CALL_LOG (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_AI_CALL_LOG_CALL_TIME
    ON HUNTTECH_AI_CALL_LOG (CALL_TIME);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_AI_CALL_LOG_FUNCTION
    ON HUNTTECH_AI_CALL_LOG (FUNCTION_CODE);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_AI_CALL_LOG_STATUS
    ON HUNTTECH_AI_CALL_LOG (STATUS);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_HUNTTECH_AI_CALL_LOG_USER'
    ) THEN
        ALTER TABLE HUNTTECH_AI_CALL_LOG
            ADD CONSTRAINT FK_HUNTTECH_AI_CALL_LOG_USER
            FOREIGN KEY (USER_ID) REFERENCES SEC_USER(ID);
    END IF;
END $$;
