-- Create HUNTTECH_OPEN_POSITION_SKILL table
CREATE TABLE IF NOT EXISTS HUNTTECH_OPEN_POSITION_SKILL (
    ID uuid PRIMARY KEY,
    VERSION integer NOT NULL,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    OPEN_POSITION_ID uuid NOT NULL,
    SKILL_ID uuid NOT NULL,
    PRIORITY integer
);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_OPEN_POSITION_SKILL_POSITION
    ON HUNTTECH_OPEN_POSITION_SKILL (OPEN_POSITION_ID);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_OPEN_POSITION_SKILL_SKILL
    ON HUNTTECH_OPEN_POSITION_SKILL (SKILL_ID);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_HUNTTECH_OPEN_POSITION_SKILL_UNQ
    ON HUNTTECH_OPEN_POSITION_SKILL (OPEN_POSITION_ID, SKILL_ID)
    WHERE DELETE_TS IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_HUNTTECH_OPEN_POSITION_SKILL_POSITION'
    ) THEN
        ALTER TABLE HUNTTECH_OPEN_POSITION_SKILL
            ADD CONSTRAINT FK_HUNTTECH_OPEN_POSITION_SKILL_POSITION
            FOREIGN KEY (OPEN_POSITION_ID) REFERENCES HUNTTECH_OPEN_POSITION(ID);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_HUNTTECH_OPEN_POSITION_SKILL_SKILL'
    ) THEN
        ALTER TABLE HUNTTECH_OPEN_POSITION_SKILL
            ADD CONSTRAINT FK_HUNTTECH_OPEN_POSITION_SKILL_SKILL
            FOREIGN KEY (SKILL_ID) REFERENCES HUNTTECH_SKILL_TREE(ID);
    END IF;
END $$;
