-- Additive AI audit security snapshots. Historical payload cleanup requires a separate approved action.
DO $$
BEGIN
    IF to_regclass('public.hunttech_ai_function_configuration') IS NULL
       OR to_regclass('public.hunttech_ai_call_log') IS NULL THEN
        RAISE EXCEPTION 'AI function and call log tables must exist before 260905-1-addAiAuditSecuritySnapshots';
    END IF;

    ALTER TABLE HUNTTECH_AI_FUNCTION_CONFIGURATION
        ADD COLUMN IF NOT EXISTS PRIVACY_POLICY_VERSION varchar(64);
    ALTER TABLE HUNTTECH_AI_CALL_LOG
        ADD COLUMN IF NOT EXISTS PRIVACY_POLICY_VERSION_SNAPSHOT varchar(64),
        ADD COLUMN IF NOT EXISTS EXTERNAL_PROCESSING_CONSENT_VERSION_SNAPSHOT varchar(64),
        ADD COLUMN IF NOT EXISTS ADMIN_FALLBACK_CONSENT_VERSION_SNAPSHOT varchar(64);

    UPDATE HUNTTECH_AI_FUNCTION_CONFIGURATION
       SET PRIVACY_POLICY_VERSION = 'llm-chat-privacy-v1'
     WHERE CODE = 'LLM_CHAT'
       AND (PRIVACY_POLICY_VERSION IS NULL OR btrim(PRIVACY_POLICY_VERSION) = '');

    UPDATE HUNTTECH_AI_CALL_LOG
       SET PRIVACY_POLICY_VERSION_SNAPSHOT = COALESCE(PRIVACY_POLICY_VERSION_SNAPSHOT, 'LEGACY_NOT_CAPTURED'),
           EXTERNAL_PROCESSING_CONSENT_VERSION_SNAPSHOT = COALESCE(EXTERNAL_PROCESSING_CONSENT_VERSION_SNAPSHOT, 'LEGACY_NOT_CAPTURED'),
           ADMIN_FALLBACK_CONSENT_VERSION_SNAPSHOT = COALESCE(ADMIN_FALLBACK_CONSENT_VERSION_SNAPSHOT, 'LEGACY_NOT_CAPTURED')
     WHERE PRIVACY_POLICY_VERSION_SNAPSHOT IS NULL
        OR EXTERNAL_PROCESSING_CONSENT_VERSION_SNAPSHOT IS NULL
        OR ADMIN_FALLBACK_CONSENT_VERSION_SNAPSHOT IS NULL;
END
$$;
