-- Отдельное согласие на автоматический fallback чата к административному AI API.
-- Идемпотентно для CUBA updateDb; existing users remain opted out.

DO $$
BEGIN
    IF to_regclass('public.hunttech_user_ai_profile') IS NULL THEN
        RAISE EXCEPTION 'HUNTTECH_USER_AI_PROFILE must exist before 260904-1-addAdminFallbackConsent';
    END IF;

    ALTER TABLE HUNTTECH_USER_AI_PROFILE
        ADD COLUMN IF NOT EXISTS ADMIN_FALLBACK_CONSENT boolean;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE
        ADD COLUMN IF NOT EXISTS ADMIN_FALLBACK_CONSENT_VERSION varchar(32);
    ALTER TABLE HUNTTECH_USER_AI_PROFILE
        ADD COLUMN IF NOT EXISTS ADMIN_FALLBACK_CONSENT_AT timestamp;

    UPDATE HUNTTECH_USER_AI_PROFILE
       SET ADMIN_FALLBACK_CONSENT = FALSE
     WHERE ADMIN_FALLBACK_CONSENT IS NULL;

    ALTER TABLE HUNTTECH_USER_AI_PROFILE
        ALTER COLUMN ADMIN_FALLBACK_CONSENT SET DEFAULT FALSE;
    ALTER TABLE HUNTTECH_USER_AI_PROFILE
        ALTER COLUMN ADMIN_FALLBACK_CONSENT SET NOT NULL;
END
$$;
^
