update HUNTTECH_AI_FUNCTION_CONFIGURATION
set ADMIN_CONFIGURATION_ID = (select ID from HUNTTECH_ADMIN_AI_CONFIGURATION where IS_ACTIVE = true order by PRIORITY_ desc limit 1),
    ADMIN_MODEL_NAME = coalesce((select DEFAULT_MODEL_NAME from HUNTTECH_ADMIN_AI_CONFIGURATION where IS_ACTIVE = true order by PRIORITY_ desc limit 1), 'deepseek-v4-flash'),
    FALLBACK_POLICY = 'FALLBACK_TO_ADMIN',
    EXECUTION_POLICY = 'USER_OVERRIDE_ALLOWED'
where CODE = 'LLM_CHAT';

update HUNTTECH_USER_AI_PROFILE
set ADMIN_FALLBACK_CONSENT = true,
    ADMIN_FALLBACK_CONSENT_VERSION = '2026-09-05-v1',
    ADMIN_FALLBACK_CONSENT_AT = current_timestamp
where USER_ID in (select ID from SEC_USER where LOGIN = 'alan');
