-- Добавление полей механизма попыток соединения и аудита в AdminAiConfiguration и AiCallLog
ALTER TABLE HUNTTECH_ADMIN_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS MAX_RETRIES integer DEFAULT 3;

ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN IF NOT EXISTS ATTEMPTS_COUNT integer DEFAULT 1;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN IF NOT EXISTS SUCCESSFUL_ATTEMPTS integer DEFAULT 0;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN IF NOT EXISTS FAILED_ATTEMPTS integer DEFAULT 0;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN IF NOT EXISTS MODEL_SWITCH_COUNT integer DEFAULT 0;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN IF NOT EXISTS FALLBACK_USED boolean DEFAULT false;

-- Инициализация исторических записей логов для консистентного отображения статистики в дашбордах
UPDATE HUNTTECH_AI_CALL_LOG
   SET SUCCESSFUL_ATTEMPTS = 1,
       FAILED_ATTEMPTS = 0,
       ATTEMPTS_COUNT = 1,
       MODEL_SWITCH_COUNT = 0,
       FALLBACK_USED = false
 WHERE (STATUS = 'SUCCESS' OR STATUS IS NULL)
   AND (SUCCESSFUL_ATTEMPTS IS NULL OR SUCCESSFUL_ATTEMPTS = 0);

UPDATE HUNTTECH_AI_CALL_LOG
   SET SUCCESSFUL_ATTEMPTS = 0,
       FAILED_ATTEMPTS = 1,
       ATTEMPTS_COUNT = 1,
       MODEL_SWITCH_COUNT = 0,
       FALLBACK_USED = false
 WHERE STATUS = 'ERROR'
   AND (FAILED_ATTEMPTS IS NULL OR FAILED_ATTEMPTS = 0);
