-- 260920-2-migrateCorporateAiConfigurations.sql
-- Миграция корпоративных AI-подключений B.AI и привязка функции фонового извлечения навыков

-- 1. Корпоративное подключение B.AI GLM 5.2 (основная бесплатная модель фонового анализа)
INSERT INTO HUNTTECH_ADMIN_AI_CONFIGURATION (
    ID, VERSION, CREATE_TS, CREATED_BY, UPDATE_TS, UPDATED_BY,
    NAME, PROVIDER_CODE, DEFAULT_MODEL_NAME, BASE_API_URL,
    IS_ACTIVE, PRIORITY_, MAX_CONTEXT_TOKENS, MAX_RETRIES, IS_FREE_MODEL,
    API_KEY_ENCRYPTED
) VALUES (
    'e1a2b3c4-0001-4000-8000-000000000001', 1, CURRENT_TIMESTAMP, 'migration', CURRENT_TIMESTAMP, 'migration',
    'B.AI GLM 5.2', 'bai', 'glm-5.2', 'https://api.b.ai/v1/chat/completions',
    true, 200, 10000, 3, true,
    'v1:a+jaaCGnDZmPLcye:q3RoH6TAuKZphHeax22WjRAJt5PrPpX5aIx4ZUGtHavNSvdkFa6DGTqcLFUZUuLS+lpB'
)
ON CONFLICT (ID) DO UPDATE SET
    NAME = EXCLUDED.NAME,
    PROVIDER_CODE = EXCLUDED.PROVIDER_CODE,
    DEFAULT_MODEL_NAME = EXCLUDED.DEFAULT_MODEL_NAME,
    BASE_API_URL = EXCLUDED.BASE_API_URL,
    IS_ACTIVE = EXCLUDED.IS_ACTIVE,
    PRIORITY_ = EXCLUDED.PRIORITY_,
    MAX_CONTEXT_TOKENS = EXCLUDED.MAX_CONTEXT_TOKENS,
    MAX_RETRIES = EXCLUDED.MAX_RETRIES,
    IS_FREE_MODEL = EXCLUDED.IS_FREE_MODEL,
    API_KEY_ENCRYPTED = EXCLUDED.API_KEY_ENCRYPTED,
    UPDATE_TS = CURRENT_TIMESTAMP,
    UPDATED_BY = 'migration';

-- 2. Корпоративное подключение B.AI Qwen 3.8 Flash (резервная бесплатная модель)
INSERT INTO HUNTTECH_ADMIN_AI_CONFIGURATION (
    ID, VERSION, CREATE_TS, CREATED_BY, UPDATE_TS, UPDATED_BY,
    NAME, PROVIDER_CODE, DEFAULT_MODEL_NAME, BASE_API_URL,
    IS_ACTIVE, PRIORITY_, MAX_CONTEXT_TOKENS, MAX_RETRIES, IS_FREE_MODEL,
    API_KEY_ENCRYPTED
) VALUES (
    'e1a2b3c4-0002-4000-8000-000000000002', 1, CURRENT_TIMESTAMP, 'migration', CURRENT_TIMESTAMP, 'migration',
    'B.AI Qwen 3.8 Flash', 'bai', 'glm-5.2', 'https://api.b.ai/v1/chat/completions',
    true, 150, 10000, 3, true,
    'v1:a+jaaCGnDZmPLcye:q3RoH6TAuKZphHeax22WjRAJt5PrPpX5aIx4ZUGtHavNSvdkFa6DGTqcLFUZUuLS+lpB'
)
ON CONFLICT (ID) DO UPDATE SET
    NAME = EXCLUDED.NAME,
    PROVIDER_CODE = EXCLUDED.PROVIDER_CODE,
    DEFAULT_MODEL_NAME = EXCLUDED.DEFAULT_MODEL_NAME,
    BASE_API_URL = EXCLUDED.BASE_API_URL,
    IS_ACTIVE = EXCLUDED.IS_ACTIVE,
    PRIORITY_ = EXCLUDED.PRIORITY_,
    MAX_CONTEXT_TOKENS = EXCLUDED.MAX_CONTEXT_TOKENS,
    MAX_RETRIES = EXCLUDED.MAX_RETRIES,
    IS_FREE_MODEL = EXCLUDED.IS_FREE_MODEL,
    API_KEY_ENCRYPTED = EXCLUDED.API_KEY_ENCRYPTED,
    UPDATE_TS = CURRENT_TIMESTAMP,
    UPDATED_BY = 'migration';

-- 3. Привязка функции SKILLS_EXTRACT_BACKGROUND к корпоративному подключению B.AI GLM 5.2
UPDATE HUNTTECH_AI_FUNCTION_CONFIGURATION
   SET ADMIN_CONFIGURATION_ID = 'e1a2b3c4-0001-4000-8000-000000000001',
       ADMIN_MODEL_NAME = 'glm-5.2',
       UPDATE_TS = CURRENT_TIMESTAMP,
       UPDATED_BY = 'migration'
 WHERE CODE = 'SKILLS_EXTRACT_BACKGROUND'
   AND DELETE_TS IS NULL;
