-- Добавление поля PRIORITY в HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS для приоритетной очереди обработки резюме
ALTER TABLE HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS
    ADD COLUMN IF NOT EXISTS PRIORITY integer DEFAULT 0;

CREATE INDEX IF NOT EXISTS IDX_CAND_CV_SKILL_ANALYSIS_PRIORITY
    ON HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS (STATUS, PRIORITY DESC, CREATE_TS ASC);
