-- Создание таблицы HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS для фонового обогащения навыков кандидатов
-- и добавление полей аудита происхождения навыка в HUNTTECH_CANDIDATE_SKILL.

CREATE TABLE IF NOT EXISTS HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS (
    ID uuid NOT NULL,
    VERSION integer NOT NULL,
    CREATE_TS timestamp without time zone,
    CREATED_BY character varying(50),
    UPDATE_TS timestamp without time zone,
    UPDATED_BY character varying(50),
    DELETE_TS timestamp without time zone,
    DELETED_BY character varying(50),
    CANDIDATE_ID uuid NOT NULL,
    CANDIDATE_CV_ID uuid NOT NULL,
    CV_CONTENT_HASH character varying(64),
    STATUS integer NOT NULL,
    SKILLS_ANALYZED_AT timestamp without time zone,
    PROCESSING_STARTED_AT timestamp without time zone,
    PROCESSING_FINISHED_AT timestamp without time zone,
    DURATION_MS bigint,
    SKILLS_CONFIGURATION_VERSION integer,
    RETRY_COUNT integer DEFAULT 0,
    NEXT_RETRY_AT timestamp without time zone,
    LAST_ERROR character varying(2000),
    PROVIDER_CODE character varying(64),
    MODEL_NAME character varying(128),
    AI_FUNCTION_CODE character varying(64),
    PROMPT_TOKENS integer,
    COMPLETION_TOKENS integer,
    TOTAL_TOKENS integer,
    ESTIMATED_COST numeric(19, 6),
    SKILLS_FOUND_COUNT integer DEFAULT 0,
    SKILLS_ADDED_COUNT integer DEFAULT 0,
    SKILLS_UPDATED_COUNT integer DEFAULT 0,
    SKILLS_UNCHANGED_COUNT integer DEFAULT 0,
    SKILLS_SKIPPED_COUNT integer DEFAULT 0,
    DELTA_DETAILS_JSON text,
    CONSTRAINT PK_HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_CAND_CV_SKILL_ANALYSIS_STATUS
    ON HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS (STATUS);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_CAND_CV_SKILL_ANALYSIS_UNQ_CV
    ON HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS (CANDIDATE_CV_ID)
    WHERE DELETE_TS IS NULL;

CREATE INDEX IF NOT EXISTS IDX_CAND_CV_SKILL_ANALYSIS_CAND
    ON HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS (CANDIDATE_ID);

CREATE INDEX IF NOT EXISTS IDX_CAND_CV_SKILL_ANALYSIS_NEXT_RETRY
    ON HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS (NEXT_RETRY_AT);

CREATE INDEX IF NOT EXISTS IDX_CAND_CV_SKILL_ANALYSIS_STARTED
    ON HUNTTECH_CANDIDATE_CV_SKILL_ANALYSIS (PROCESSING_STARTED_AT);

-- Добавление полей SOURCE_TYPE и SOURCE_CV_ID в HUNTTECH_CANDIDATE_SKILL
ALTER TABLE HUNTTECH_CANDIDATE_SKILL
    ADD COLUMN IF NOT EXISTS SOURCE_TYPE character varying(16);

ALTER TABLE HUNTTECH_CANDIDATE_SKILL
    ADD COLUMN IF NOT EXISTS SOURCE_CV_ID uuid;

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_CANDIDATE_SKILL_SOURCE_CV
    ON HUNTTECH_CANDIDATE_SKILL (SOURCE_CV_ID);
