-- Добавление полей основной нейросети, количества повторных попыток и приоритета в HUNTTECH_USER_AI_CONFIGURATION
-- Идемпотентно для CUBA updateDb

ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS IS_PRIMARY BOOLEAN DEFAULT false;
ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS MAX_RETRIES INTEGER DEFAULT 2;
ALTER TABLE HUNTTECH_USER_AI_CONFIGURATION ADD COLUMN IF NOT EXISTS PRIORITY_ INTEGER DEFAULT 10;
