-- HRM HuntTech: Создание таблиц аудита AI-подбора и решений рекрутера (Этап 3)

CREATE TABLE IF NOT EXISTS HUNTTECH_VACANCY_CANDIDATE_MATCH_RUN (
    ID UUID NOT NULL PRIMARY KEY,
    VERSION INTEGER NOT NULL DEFAULT 1,
    CREATE_TS TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATE_TS TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_BY VARCHAR(50),
    DELETE_TS TIMESTAMP WITHOUT TIME ZONE,
    DELETED_BY VARCHAR(50),

    OPEN_POSITION_ID UUID REFERENCES HUNTTECH_OPEN_POSITION(ID) ON DELETE SET NULL,
    JOB_CANDIDATE_ID UUID REFERENCES HUNTTECH_JOB_CANDIDATE(ID) ON DELETE SET NULL,
    RECRUITER_ID UUID REFERENCES SEC_USER(ID) ON DELETE SET NULL,
    RUN_TIME TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONFIGURATION_VERSION INTEGER,
    AI_FUNCTION_CODE VARCHAR(64),
    CANDIDATES_REVIEWED_COUNT INTEGER DEFAULT 0,
    TAKEN_INTO_WORK_COUNT INTEGER DEFAULT 0,
    REJECTED_COUNT INTEGER DEFAULT 0,
    POSTPONED_COUNT INTEGER DEFAULT 0,
    OUTREACH_DRAFTS_COUNT INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_MATCH_RUN_VACANCY ON HUNTTECH_VACANCY_CANDIDATE_MATCH_RUN(OPEN_POSITION_ID, RUN_TIME DESC) WHERE DELETE_TS IS NULL;
CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_MATCH_RUN_RECRUITER ON HUNTTECH_VACANCY_CANDIDATE_MATCH_RUN(RECRUITER_ID, RUN_TIME DESC) WHERE DELETE_TS IS NULL;

CREATE TABLE IF NOT EXISTS HUNTTECH_VACANCY_CANDIDATE_MATCH_FEEDBACK (
    ID UUID NOT NULL PRIMARY KEY,
    VERSION INTEGER NOT NULL DEFAULT 1,
    CREATE_TS TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    UPDATE_TS TIMESTAMP WITHOUT TIME ZONE,
    UPDATED_BY VARCHAR(50),
    DELETE_TS TIMESTAMP WITHOUT TIME ZONE,
    DELETED_BY VARCHAR(50),

    MATCH_RUN_ID UUID REFERENCES HUNTTECH_VACANCY_CANDIDATE_MATCH_RUN(ID) ON DELETE SET NULL,
    OPEN_POSITION_ID UUID NOT NULL REFERENCES HUNTTECH_OPEN_POSITION(ID) ON DELETE CASCADE,
    JOB_CANDIDATE_ID UUID NOT NULL REFERENCES HUNTTECH_JOB_CANDIDATE(ID) ON DELETE CASCADE,
    RECRUITER_ID UUID NOT NULL REFERENCES SEC_USER(ID) ON DELETE CASCADE,
    AI_SCORE INTEGER,
    DECISION INTEGER NOT NULL DEFAULT 10,
    REJECTION_REASON VARCHAR(255),
    ITERACTION_TYPE_ID UUID REFERENCES HUNTTECH_ITERACTION(ID) ON DELETE SET NULL,
    ITERACTION_LIST_ID UUID REFERENCES HUNTTECH_ITERACTION_LIST(ID) ON DELETE SET NULL,
    COMMENT_ TEXT,
    DECISION_TIME TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_MATCH_FEEDBACK_VAC_CAND ON HUNTTECH_VACANCY_CANDIDATE_MATCH_FEEDBACK(OPEN_POSITION_ID, JOB_CANDIDATE_ID) WHERE DELETE_TS IS NULL;
CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_MATCH_FEEDBACK_RECRUITER ON HUNTTECH_VACANCY_CANDIDATE_MATCH_FEEDBACK(RECRUITER_ID, DECISION_TIME DESC) WHERE DELETE_TS IS NULL;
CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_MATCH_FEEDBACK_DECISION ON HUNTTECH_VACANCY_CANDIDATE_MATCH_FEEDBACK(DECISION, DECISION_TIME DESC) WHERE DELETE_TS IS NULL;
