-- 260912-1-addPositionIconFields.sql
-- Добавление полей пиктограммы должности (FileDescriptor и BLOB) в HUNTTECH_POSITION

ALTER TABLE HUNTTECH_POSITION ADD COLUMN IF NOT EXISTS FILE_POSITION_ICON_ID UUID;
ALTER TABLE HUNTTECH_POSITION ADD COLUMN IF NOT EXISTS ICON_IMAGE BYTEA;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_HUNTTECH_POSITION_ON_FILE_ICON') THEN
        ALTER TABLE HUNTTECH_POSITION ADD CONSTRAINT FK_HUNTTECH_POSITION_ON_FILE_ICON
            FOREIGN KEY (FILE_POSITION_ICON_ID) REFERENCES SYS_FILE(ID);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS IDX_HUNTTECH_POSITION_ON_FILE_ICON ON HUNTTECH_POSITION(FILE_POSITION_ICON_ID);
