alter table HUNTTECH_CANDIDATE_CV add constraint FK_HUNTTECH_CANDIDATE_CV_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_CANDIDATE_CV_ON_OWNER on HUNTTECH_CANDIDATE_CV (OWNER_ID);
