alter table HUNTTECH_CANDIDATE_CV add constraint FK_HUNTTECH_CANDIDATE_CV_ON_CANDIDATE foreign key (CANDIDATE_ID) references HUNTTECH_JOB_CANDIDATE(ID);
create index IDX_HUNTTECH_CANDIDATE_CV_ON_CANDIDATE on HUNTTECH_CANDIDATE_CV (CANDIDATE_ID);
