alter table ITPEARLS_JOB_HISTORY add constraint FK_ITPEARLS_JOB_HISTORY_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID);
create index IDX_ITPEARLS_JOB_HISTORY_ON_CANDIDATE on ITPEARLS_JOB_HISTORY (CANDIDATE_ID);
