alter table ITPEARLS_SETUP add constraint FK_ITPEARLS_SETUP_ON_PARAM_USER foreign key (PARAM_USER_ID) references SEC_USER(ID);
create unique index IDX_ITPEARLS_SETUP_UNIQ_PERAM_NAME on ITPEARLS_SETUP (PERAM_NAME) ;
create index IDX_ITPEARLS_SETUP_ON_PARAM_USER on ITPEARLS_SETUP (PARAM_USER_ID);
