alter table HUNTTECH_JOB_HISTORY add constraint FK_HUNTTECH_JOB_HISTORY_ON_CANDIDATE foreign key (CANDIDATE_ID) references HUNTTECH_JOB_CANDIDATE(ID);
create index IDX_HUNTTECH_JOB_HISTORY_ON_CANDIDATE on HUNTTECH_JOB_HISTORY (CANDIDATE_ID);
