alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_FILE_CV foreign key (FILE_CV_ID) references SYS_FILE(ID);
create index IDX_ITPEARLS_CANDIDATE_CV_ON_FILE_CV on ITPEARLS_CANDIDATE_CV (FILE_CV_ID);
