alter table HUNTTECH_USER_AI_CONFIGURATION add constraint FK_HUNTTECH_USER_AI_CONFIGURATION_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_USER_AI_CONFIGURATION_USER on HUNTTECH_USER_AI_CONFIGURATION (USER_ID);
create unique index IDX_HUNTTECH_VACANCY_PROMPT_TEMPLATE_CODE on HUNTTECH_VACANCY_PROMPT_TEMPLATE (CODE) where DELETE_TS is null ;
