alter table ITPEARLS_USER_AI_CONFIGURATION add constraint FK_ITPEARLS_USER_AI_CONFIGURATION_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ITPEARLS_USER_AI_CONFIGURATION_USER on ITPEARLS_USER_AI_CONFIGURATION (USER_ID);
create unique index IDX_ITPEARLS_VACANCY_PROMPT_TEMPLATE_CODE on ITPEARLS_VACANCY_PROMPT_TEMPLATE (CODE) where DELETE_TS is null ;
