create index IDX_HUNTTECH_PROJECT_ACTIVE_NAME on HUNTTECH_PROJECT (PROJECT_IS_CLOSED, PROJECT_NAME, ID);

create index IDX_HUNTTECH_PROJECT_TREE_PICKER_ACTIVE_NAME on HUNTTECH_PROJECT (PROJECT_IS_CLOSED, PROJECT_NAME, ID);

create index IDX_HUNTTECH_PROJECT_DEFAULT_ACTIVE on HUNTTECH_PROJECT (DEFAULT_PROJECT, ID);

create index IDX_HUNTTECH_OPEN_POSITION_OPEN_PROJECT on HUNTTECH_OPEN_POSITION (OPEN_CLOSE, PROJECT_NAME_ID);
