-- Добавление полей механизма попыток соединения и аудита в AdminAiConfiguration и AiCallLog (HSQL)
ALTER TABLE HUNTTECH_ADMIN_AI_CONFIGURATION ADD COLUMN MAX_RETRIES integer DEFAULT 3;

ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN ATTEMPTS_COUNT integer DEFAULT 1;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN SUCCESSFUL_ATTEMPTS integer DEFAULT 0;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN FAILED_ATTEMPTS integer DEFAULT 0;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN MODEL_SWITCH_COUNT integer DEFAULT 0;
ALTER TABLE HUNTTECH_AI_CALL_LOG ADD COLUMN FALLBACK_USED boolean DEFAULT false;
