-- HSQL update for vacancy checklist in VACANCY_SMART_PARSE_JSON
UPDATE HUNTTECH_AI_FUNCTION_CONFIGURATION
SET CONFIGURATION_VERSION = CONFIGURATION_VERSION + 1
WHERE CODE = 'VACANCY_SMART_PARSE_JSON';
