-- HSQL update for STANDARDIZE_VACANCY and VACANCY_SMART_PARSE_JSON
UPDATE HUNTTECH_AI_FUNCTION_CONFIGURATION
SET CONFIGURATION_VERSION = CONFIGURATION_VERSION + 1
WHERE CODE IN ('STANDARDIZE_VACANCY', 'VACANCY_SMART_PARSE_JSON');
