-- HSQL update for LLM_CHAT system prompt version with Yandex 360
UPDATE HUNTTECH_AI_FUNCTION_CONFIGURATION
SET CONFIGURATION_VERSION = CONFIGURATION_VERSION + 1,
    UPDATE_TS = CURRENT_TIMESTAMP
WHERE CODE = 'LLM_CHAT' AND DELETE_TS IS NULL;
