create unique index IDX_ITPEARLS_REGION_UNIQ_REGION_EN_NAME on ITPEARLS_REGION (REGION_EN_NAME) ;
create unique index IDX_ITPEARLS_REGION_UNIQ_REGION_RU_NAME on ITPEARLS_REGION (REGION_RU_NAME) ;
create unique index IDX_ITPEARLS_REGION_UNIQ_REGION_CODE on ITPEARLS_REGION (REGION_CODE) ;
