alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_COMPANY_GROUP foreign key (COMPANY_GROUP_ID) references ITPEARLS_COMPANY_GROUP(ID);
create index IDX_ITPEARLS_COMPANY_ON_COMPANY_GROUP on ITPEARLS_COMPANY (COMPANY_GROUP_ID);
