alter table HUNTTECH_COMPANY add constraint FK_HUNTTECH_COMPANY_ON_COMPANY_OWNERSHIP foreign key (COMPANY_OWNERSHIP_ID) references HUNTTECH_OWNERSHUP(ID);
create unique index IDX_HUNTTECH_COMPANY_UNIQ_COMPANY_SHORT_NAME on HUNTTECH_COMPANY (COMPANY_SHORT_NAME) ;
create unique index IDX_HUNTTECH_COMPANY_UNIQ_COMPANY_EN_SHORT_NAME on HUNTTECH_COMPANY (COMPANY_EN_SHORT_NAME) ;
create unique index IDX_HUNTTECH_COMPANY_UNIQ_COMPANY_EN_NAME on HUNTTECH_COMPANY (COMPANY_EN_NAME) ;
create unique index IDX_HUNTTECH_COMPANY_UNIQ_COMANY_NAME on HUNTTECH_COMPANY (COMANY_NAME) ;
create index IDX_HUNTTECH_COMPANY_ON_COMPANY_OWNERSHIP on HUNTTECH_COMPANY (COMPANY_OWNERSHIP_ID);
