alter table HUNTTECH_SKILL add constraint FK_HUNTTECH_SKILL_ON_SKILL_TYPE foreign key (SKILL_TYPE_ID) references HUNTTECH_SPECIALISATION(ID);
create unique index IDX_HUNTTECH_SKILL_UNIQ_SKILL_NAME on HUNTTECH_SKILL (SKILL_NAME) ;
create index IDX_HUNTTECH_SKILL_ON_SKILL_TYPE on HUNTTECH_SKILL (SKILL_TYPE_ID);
