alter table ITPEARLS_OPEN_POSITION alter column PROJECT_ID rename to PROJECT_ID__U71464 ^
alter table ITPEARLS_OPEN_POSITION alter column PROJECT_ID__U71464 set null ;
alter table ITPEARLS_OPEN_POSITION drop constraint FK_ITPEARLS_OPEN_POSITION_ON_PROJECT ;
drop index IDX_ITPEARLS_OPEN_POSITION_ON_PROJECT ;
