create unique index IDX_HUNTTECH_REGION_UNIQ_REGION_EN_NAME on HUNTTECH_REGION (REGION_EN_NAME) ;
create unique index IDX_HUNTTECH_REGION_UNIQ_REGION_RU_NAME on HUNTTECH_REGION (REGION_RU_NAME) ;
create unique index IDX_HUNTTECH_REGION_UNIQ_REGION_CODE on HUNTTECH_REGION (REGION_CODE) ;
