alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_PROJECT foreign key (PROJECT_ID) references ITPEARLS_PROJECT(ID);
create index IDX_ITPEARLS_OPEN_POSITION_ON_PROJECT on ITPEARLS_OPEN_POSITION (PROJECT_ID);
