alter table HUNTTECH_OPEN_POSITION add constraint FK_HUNTTECH_OPEN_POSITION_ON_PROJECT foreign key (PROJECT_ID) references HUNTTECH_PROJECT(ID);
create index IDX_HUNTTECH_OPEN_POSITION_ON_PROJECT on HUNTTECH_OPEN_POSITION (PROJECT_ID);
