alter table HUNTTECH_COMPANY add constraint FK_HUNTTECH_COMPANY_ON_COMPANY_GROUP foreign key (COMPANY_GROUP_ID) references HUNTTECH_COMPANY_GROUP(ID);
create index IDX_HUNTTECH_COMPANY_ON_COMPANY_GROUP on HUNTTECH_COMPANY (COMPANY_GROUP_ID);
