alter table HUNTTECH_CITY add constraint FK_HUNTTECH_CITY_ON_CITY_REGION foreign key (CITY_REGION_ID) references HUNTTECH_REGION(ID);
create unique index IDX_HUNTTECH_CITY_UNIQ_CITY_EN_NAME on HUNTTECH_CITY (CITY_EN_NAME) ;
create unique index IDX_HUNTTECH_CITY_UNIQ_CITY_RU_NAME on HUNTTECH_CITY (CITY_RU_NAME) ;
create unique index IDX_HUNTTECH_CITY_UNIQ_CITY_PHONE_CODE on HUNTTECH_CITY (CITY_PHONE_CODE) ;
create index IDX_HUNTTECH_CITY_ON_CITY_REGION on HUNTTECH_CITY (CITY_REGION_ID);
