alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_COMPANY_OWNERSHIP foreign key (COMPANY_OWNERSHIP_ID) references ITPEARLS_OWNERSHUP(ID);
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMPANY_SHORT_NAME on ITPEARLS_COMPANY (COMPANY_SHORT_NAME) ;
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMPANY_EN_SHORT_NAME on ITPEARLS_COMPANY (COMPANY_EN_SHORT_NAME) ;
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMPANY_EN_NAME on ITPEARLS_COMPANY (COMPANY_EN_NAME) ;
create unique index IDX_ITPEARLS_COMPANY_UNIQ_COMANY_NAME on ITPEARLS_COMPANY (COMANY_NAME) ;
create index IDX_ITPEARLS_COMPANY_ON_COMPANY_OWNERSHIP on ITPEARLS_COMPANY (COMPANY_OWNERSHIP_ID);
