alter table HUNTTECH_FIRMA add constraint FK_HUNTTECH_FIRMA_ON_LEGAL_TYPE foreign key (LEGAL_TYPE_ID) references HUNTTECH_OWNERSHIP(ID);
create unique index IDX_HUNTTECH_FIRMA_UNIQ_COMPANY_NAME on HUNTTECH_FIRMA (COMPANY_NAME) ;
create index IDX_HUNTTECH_FIRMA_ON_LEGAL_TYPE on HUNTTECH_FIRMA (LEGAL_TYPE_ID);
