alter table HUNTTECH_MAIN_LIST alter column CONTACT_NAME_ID rename to CONTACT_NAME_ID__U38383 ^
alter table HUNTTECH_MAIN_LIST drop constraint FK_HUNTTECH_MAIN_LIST_ON_CONTACT_NAME ;
drop index IDX_HUNTTECH_MAIN_LIST_ON_CONTACT_NAME ;
