alter table ITPEARLS_CITY add constraint FK_ITPEARLS_CITY_ON_CITY_REGION foreign key (CITY_REGION_ID) references ITPEARLS_REGION(ID);
create unique index IDX_ITPEARLS_CITY_UNIQ_CITY_EN_NAME on ITPEARLS_CITY (CITY_EN_NAME) ;
create unique index IDX_ITPEARLS_CITY_UNIQ_CITY_RU_NAME on ITPEARLS_CITY (CITY_RU_NAME) ;
create unique index IDX_ITPEARLS_CITY_UNIQ_CITY_PHONE_CODE on ITPEARLS_CITY (CITY_PHONE_CODE) ;
create index IDX_ITPEARLS_CITY_ON_CITY_REGION on ITPEARLS_CITY (CITY_REGION_ID);
