alter table ITPEARLS_FIRMA add constraint FK_ITPEARLS_FIRMA_ON_LEGAL_TYPE foreign key (LEGAL_TYPE_ID) references ITPEARLS_OWNERSHIP(ID);
create unique index IDX_ITPEARLS_FIRMA_UNIQ_COMPANY_NAME on ITPEARLS_FIRMA (COMPANY_NAME) ;
create index IDX_ITPEARLS_FIRMA_ON_LEGAL_TYPE on ITPEARLS_FIRMA (LEGAL_TYPE_ID);
