alter table HUNTTECH_OPEN_POSITION alter column PROJECT_ID rename to PROJECT_ID__U71464 ^
alter table HUNTTECH_OPEN_POSITION alter column PROJECT_ID__U71464 set null ;
alter table HUNTTECH_OPEN_POSITION drop constraint FK_HUNTTECH_OPEN_POSITION_ON_PROJECT ;
drop index IDX_HUNTTECH_OPEN_POSITION_ON_PROJECT ;
