alter table HUNTTECH_PERSON add constraint FK_HUNTTECH_PERSON_ON_POSITION_COUNTRY foreign key (POSITION_COUNTRY_ID) references HUNTTECH_COUNTRY(ID);
alter table HUNTTECH_PERSON add constraint FK_HUNTTECH_PERSON_ON_PERSON_POSITION foreign key (PERSON_POSITION_ID) references HUNTTECH_POSITION(ID);
create index IDX_HUNTTECH_PERSON_ON_POSITION_COUNTRY on HUNTTECH_PERSON (POSITION_COUNTRY_ID);
create index IDX_HUNTTECH_PERSON_ON_PERSON_POSITION on HUNTTECH_PERSON (PERSON_POSITION_ID);
