alter table HUNTTECH_COMPANY add constraint FK_HUNTTECH_COMPANY_ON_COMPANY_DIRECTOR foreign key (COMPANY_DIRECTOR_ID) references HUNTTECH_PERSON(ID);
create index IDX_HUNTTECH_COMPANY_ON_COMPANY_DIRECTOR on HUNTTECH_COMPANY (COMPANY_DIRECTOR_ID);
