alter table HUNTTECH_REGION add constraint FK_HUNTTECH_REGION_ON_REGION_COUNTRY foreign key (REGION_COUNTRY_ID) references HUNTTECH_COUNTRY(ID);
create index IDX_HUNTTECH_REGION_ON_REGION_COUNTRY on HUNTTECH_REGION (REGION_COUNTRY_ID);
