alter table HUNTTECH_SKILL alter column SPECIALISATION_ID rename to SPECIALISATION_ID__U86432 ^
alter table HUNTTECH_SKILL drop constraint FK_HUNTTECH_SKILL_ON_SPECIALISATION ;
drop index IDX_HUNTTECH_SKILL_ON_SPECIALISATION ;
alter table HUNTTECH_SKILL add column SKILL_SPECIALISATION_ID varchar(36) ;
