alter table ITPEARLS_PROJECT alter column PROJECT_COMPANY_ID rename to PROJECT_COMPANY_ID__U87722 ^
alter table ITPEARLS_PROJECT alter column PROJECT_COMPANY_ID__U87722 set null ;
alter table ITPEARLS_PROJECT drop constraint FK_ITPEARLS_PROJECT_ON_PROJECT_COMPANY ;
drop index IDX_ITPEARLS_PROJECT_ON_PROJECT_COMPANY ;
