alter table ITPEARLS_COMPANY alter column COMPANY_GROUP_ID rename to COMPANY_GROUP_ID__U10786 ^
alter table ITPEARLS_COMPANY drop constraint FK_ITPEARLS_COMPANY_ON_COMPANY_GROUP ;
drop index IDX_ITPEARLS_COMPANY_ON_COMPANY_GROUP ;
