alter table HUNTTECH_SKILL_TREE add constraint FK_HUNTTECH_SKILL_TREE_ON_SKILL_TREE foreign key (SKILL_TREE_ID) references HUNTTECH_SKILL_TREE(ID);
create unique index IDX_HUNTTECH_SKILL_TREE_UNIQ_SKILL_NAME on HUNTTECH_SKILL_TREE (SKILL_NAME) ;
create index IDX_HUNTTECH_SKILL_TREE_ON_SKILL_TREE on HUNTTECH_SKILL_TREE (SKILL_TREE_ID);
