alter table ITPEARLS_SKILL_TREE alter column SPECIALISATION_ID rename to SPECIALISATION_ID__U51448 ^
alter table ITPEARLS_SKILL_TREE drop constraint FK_ITPEARLS_SKILL_TREE_ON_SPECIALISATION ;
drop index IDX_ITPEARLS_SKILL_TREE_ON_SPECIALISATION ;
alter table ITPEARLS_SKILL_TREE add column JOB_CANDIDATE_ID varchar(36) ;
