alter table HUNTTECH_SKILL add constraint FK_HUNTTECH_SKILL_ON_SKILL_TREE_LINK foreign key (SKILL_TREE_LINK_ID) references HUNTTECH_SKILL(ID);
create index IDX_HUNTTECH_SKILL_ON_SKILL_TREE_LINK on HUNTTECH_SKILL (SKILL_TREE_LINK_ID);
