alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID);
create index IDX_ITPEARLS_CANDIDATE_CV_ON_CANDIDATE on ITPEARLS_CANDIDATE_CV (CANDIDATE_ID);
