alter table HUNTTECH_PROJECT add constraint FK_HUNTTECH_PROJECT_ON_PROJECT_OWNER foreign key (PROJECT_OWNER_ID) references HUNTTECH_PERSON(ID);
create index IDX_HUNTTECH_PROJECT_ON_PROJECT_OWNER on HUNTTECH_PROJECT (PROJECT_OWNER_ID);
