alter table HUNTTECH_CANDIDATE_CV add constraint FK_HUNTTECH_CANDIDATE_CV_ON_FILE_CV foreign key (FILE_CV_ID) references SYS_FILE(ID);
create index IDX_HUNTTECH_CANDIDATE_CV_ON_FILE_CV on HUNTTECH_CANDIDATE_CV (FILE_CV_ID);
