alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_CITY_OF_COMPANY foreign key (CITY_OF_COMPANY_ID) references ITPEARLS_CITY(ID);
create index IDX_ITPEARLS_COMPANY_ON_CITY_OF_COMPANY on ITPEARLS_COMPANY (CITY_OF_COMPANY_ID);
