alter table HUNTTECH_PROJECT alter column PROJECT_COMPANY_ID rename to PROJECT_COMPANY_ID__U87722 ^
alter table HUNTTECH_PROJECT alter column PROJECT_COMPANY_ID__U87722 set null ;
alter table HUNTTECH_PROJECT drop constraint FK_HUNTTECH_PROJECT_ON_PROJECT_COMPANY ;
drop index IDX_HUNTTECH_PROJECT_ON_PROJECT_COMPANY ;
