alter table ITPEARLS_SKILL add constraint FK_ITPEARLS_SKILL_ON_SKILL_TREE_LINK foreign key (SKILL_TREE_LINK_ID) references ITPEARLS_SKILL(ID);
create index IDX_ITPEARLS_SKILL_ON_SKILL_TREE_LINK on ITPEARLS_SKILL (SKILL_TREE_LINK_ID);
