alter table HUNTTECH_COMPANY add constraint FK_HUNTTECH_COMPANY_ON_CITY_OF_COMPANY foreign key (CITY_OF_COMPANY_ID) references HUNTTECH_CITY(ID);
create index IDX_HUNTTECH_COMPANY_ON_CITY_OF_COMPANY on HUNTTECH_COMPANY (CITY_OF_COMPANY_ID);
