alter table ITPEARLS_PROJECT add constraint FK_ITPEARLS_PROJECT_ON_PROJECT_OWNER foreign key (PROJECT_OWNER_ID) references ITPEARLS_PERSON(ID);
create index IDX_ITPEARLS_PROJECT_ON_PROJECT_OWNER on ITPEARLS_PROJECT (PROJECT_OWNER_ID);
