alter table ITPEARLS_SKILLS_TREE add constraint FK_ITPEARLS_SKILLS_TREE_ON_SKILL_TREE foreign key (SKILL_TREE_ID) references ITPEARLS_SKILLS_TREE(ID);
create unique index IDX_ITPEARLS_SKILLS_TREE_UNIQ_SKILL_NAME on ITPEARLS_SKILLS_TREE (SKILL_NAME) ;
create index IDX_ITPEARLS_SKILLS_TREE_ON_SKILL_TREE on ITPEARLS_SKILLS_TREE (SKILL_TREE_ID);
