alter table HUNTTECH_COMPANY alter column COMPANY_GROUP_ID rename to COMPANY_GROUP_ID__U10786 ^
alter table HUNTTECH_COMPANY drop constraint FK_HUNTTECH_COMPANY_ON_COMPANY_GROUP ;
drop index IDX_HUNTTECH_COMPANY_ON_COMPANY_GROUP ;
