alter table ITPEARLS_COMPANY_GROUP alter column COMPANY_EN_GROUP_NAME rename to COMPANY_EN_GROUP_NAME__U97365 ^
alter table ITPEARLS_COMPANY_GROUP alter column COMPANY_EN_GROUP_NAME__U97365 set null ;
