alter table HUNTTECH_SKILLS_TREE add constraint FK_HUNTTECH_SKILLS_TREE_ON_SKILL_TREE foreign key (SKILL_TREE_ID) references HUNTTECH_SKILLS_TREE(ID);
create unique index IDX_HUNTTECH_SKILLS_TREE_UNIQ_SKILL_NAME on HUNTTECH_SKILLS_TREE (SKILL_NAME) ;
create index IDX_HUNTTECH_SKILLS_TREE_ON_SKILL_TREE on HUNTTECH_SKILLS_TREE (SKILL_TREE_ID);
