alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_ITPEARLS_OPEN_POSITION_ON_OWNER on ITPEARLS_OPEN_POSITION (OWNER_ID);
