alter table HUNTTECH_OPEN_POSITION add constraint FK_HUNTTECH_OPEN_POSITION_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_OPEN_POSITION_ON_OWNER on HUNTTECH_OPEN_POSITION (OWNER_ID);
