alter table HUNTTECH_INTERVIEW add constraint FK_HUNTTECH_INTERVIEW_ON_CANDIDATE foreign key (CANDIDATE_ID) references HUNTTECH_JOB_CANDIDATE(ID);
alter table HUNTTECH_INTERVIEW add constraint FK_HUNTTECH_INTERVIEW_ON_CANDIDATE_CV foreign key (CANDIDATE_CV_ID) references HUNTTECH_CANDIDATE_CV(ID);
alter table HUNTTECH_INTERVIEW add constraint FK_HUNTTECH_INTERVIEW_ON_RECRUTIER foreign key (RECRUTIER_ID) references SEC_USER(ID);
alter table HUNTTECH_INTERVIEW add constraint FK_HUNTTECH_INTERVIEW_ON_RESEARCHER foreign key (RESEARCHER_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_INTERVIEW_ON_CANDIDATE on HUNTTECH_INTERVIEW (CANDIDATE_ID);
create index IDX_HUNTTECH_INTERVIEW_ON_CANDIDATE_CV on HUNTTECH_INTERVIEW (CANDIDATE_CV_ID);
create index IDX_HUNTTECH_INTERVIEW_ON_RECRUTIER on HUNTTECH_INTERVIEW (RECRUTIER_ID);
create index IDX_HUNTTECH_INTERVIEW_ON_RESEARCHER on HUNTTECH_INTERVIEW (RESEARCHER_ID);
