alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID);
alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_CANDIDATE_CV foreign key (CANDIDATE_CV_ID) references ITPEARLS_CANDIDATE_CV(ID);
alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_RECRUTIER foreign key (RECRUTIER_ID) references SEC_USER(ID);
alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_RESEARCHER foreign key (RESEARCHER_ID) references SEC_USER(ID);
create index IDX_ITPEARLS_INTERVIEW_ON_CANDIDATE on ITPEARLS_INTERVIEW (CANDIDATE_ID);
create index IDX_ITPEARLS_INTERVIEW_ON_CANDIDATE_CV on ITPEARLS_INTERVIEW (CANDIDATE_CV_ID);
create index IDX_ITPEARLS_INTERVIEW_ON_RECRUTIER on ITPEARLS_INTERVIEW (RECRUTIER_ID);
create index IDX_ITPEARLS_INTERVIEW_ON_RESEARCHER on ITPEARLS_INTERVIEW (RESEARCHER_ID);
