alter table HUNTTECH_EMAILER add constraint FK_HUNTTECH_EMAILER_ON_FROM_EMAIL foreign key (FROM_EMAIL_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_EMAILER_ON_FROM_EMAIL on HUNTTECH_EMAILER (FROM_EMAIL_ID);
