alter table ITPEARLS_EMAILER add constraint FK_ITPEARLS_EMAILER_ON_FROM_EMAIL foreign key (FROM_EMAIL_ID) references SEC_USER(ID);
create index IDX_ITPEARLS_EMAILER_ON_FROM_EMAIL on ITPEARLS_EMAILER (FROM_EMAIL_ID);
