alter table HUNTTECH_EMAILER add constraint FK_HUNTTECH_EMAILER_ON_TO_EMAIL foreign key (TO_EMAIL_ID) references HUNTTECH_JOB_CANDIDATE(ID);
create index IDX_HUNTTECH_EMAILER_ON_TO_EMAIL on HUNTTECH_EMAILER (TO_EMAIL_ID);
