alter table ITPEARLS_EMAILER add constraint FK_ITPEARLS_EMAILER_ON_TO_EMAIL foreign key (TO_EMAIL_ID) references ITPEARLS_JOB_CANDIDATE(ID);
create index IDX_ITPEARLS_EMAILER_ON_TO_EMAIL on ITPEARLS_EMAILER (TO_EMAIL_ID);
