alter table HUNTTECH_STAFFING_TABLE add constraint FK_HUNTTECH_STAFFING_TABLE_ON_GRADE foreign key (GRADE_ID) references HUNTTECH_GRADE(ID);
create index IDX_HUNTTECH_STAFFING_TABLE_ON_GRADE on HUNTTECH_STAFFING_TABLE (GRADE_ID);
