alter table HUNTTECH_OPEN_POSITION add constraint FK_HUNTTECH_OPEN_POSITION_ON_GRADE foreign key (GRADE_ID) references HUNTTECH_GRADE(ID);
create index IDX_HUNTTECH_OPEN_POSITION_ON_GRADE on HUNTTECH_OPEN_POSITION (GRADE_ID);
