-- alter table HUNTTECH_APPLICATION_RECRUITMENT add column APPLICATION_RECRUITMENT_LIST_ID uuid ^
-- update HUNTTECH_APPLICATION_RECRUITMENT set APPLICATION_RECRUITMENT_LIST_ID = <default_value> ;
-- alter table HUNTTECH_APPLICATION_RECRUITMENT alter column APPLICATION_RECRUITMENT_LIST_ID set not null ;
alter table HUNTTECH_APPLICATION_RECRUITMENT add column APPLICATION_RECRUITMENT_LIST_ID uuid not null ;
