alter table ITPEARLS_APPLICATION_RECRUITMENT_LIST add column PROJECT_DEPARTMENT_ID uuid ;
alter table ITPEARLS_APPLICATION_RECRUITMENT_LIST add column PROJECT_ID uuid ;
alter table ITPEARLS_APPLICATION_RECRUITMENT_LIST add column COMPANY_ID uuid ;
