alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_GRADE foreign key (GRADE_ID) references ITPEARLS_GRADE(ID);
create index IDX_ITPEARLS_OPEN_POSITION_ON_GRADE on ITPEARLS_OPEN_POSITION (GRADE_ID);
