###############################################################################
#                              Configuration                                  #
###############################################################################
cuba.dbmsType=postgres
cuba.springContextConfig=+com/company/itpearls/spring.xml
cuba.persistenceConfig=+com/company/itpearls/persistence.xml
cuba.metadataConfig=+com/company/itpearls/metadata.xml
cuba.viewsConfig=+com/company/itpearls/views.xml
cuba.mainMessagePack=+com.company.itpearls.core
cuba.keyForSecurityTokenEncryption=rnXYwpnwv5OouW2w
cuba.anonymousSessionId=beb1d62c-3549-cc4a-3e04-e4f29e5f0f43
cuba.supportEmail=no-reply@itpearls.ru
###############################################################################
#                                  Other                                      #
###############################################################################
cuba.webContextName=app-core
cuba.availableLocales=English|en;Russian|ru
cuba.localeSelectVisible=true
cuba.schedulingActive=true
cuba.email.fromAddress=a.ananyev@itpearls.ru
cuba.email.smtpHost=smtp.mail.ru
cuba.email.smtpAuthRequired=true
cuba.email.smtpPort=465
cuba.email.smtpUser=a.ananyev@itpearls.ru
cuba.email.smtpPassword=NSEc9j2jnqi84LYCPPVL
cuba.email.smtpSslEnabled=true
cuba.ftsConfig=+com/company/itpearls/fts.xml
cuba.httpSessionExpirationTimeoutSec=900
cuba.userSessionExpirationTimeoutSec=900
cuba.security.rolesPolicyVersion=1
cuba.security.defaultPermissionValuesConfigEnabled=true
cuba.security.minimalRoleIsDefault=false
cuba.connectionUrlList=http://localhost:8080/app-core
# cuba.connectionUrlList=http://hr-new.it-pearls.ru:8080/app-core
cuba.dataSourceProvider=jndi
# cuba.dataSource.host=hr.it-pearls.ru
cuba.queryCache.enabled=true
cuba.queryCache.maxSize=1000
cuba.useReadOnlyTransactionForLoad=false
cuba.fileStorageDir=/opt/app_home/fileStorage,/cuba-app/itpearls-recruiting/fileStorage,/Users/alekseyananyev/StudioProjects/fileStorage/cuba-app/itpearls-recruiting/fileStorage
# cuba.fileStorageDir=/Users/alekseyananyev/StudioProjects/fileStorage/cuba-app/itpearls-recruiting/fileStorage
cuba.tempDir=/opt/app_home/fileStorage/temp
# cuba.tempDir=/Users/alekseyananyev/StudioProjects/fileStorage/cuba-app/itpearls-recruiting/fileStorage/temp
eclipselink.cache.shared.itpearls_OpenPosition=true
eclipselink.cache.size.itpearls_OpenPosition=1000
cuba.useLocalServiceInvocation=true
eclipselink.cache.shared.itpearls_IteractionList=true
eclipselink.cache.size.itpearls_IteractionList=10000
# eclipselink.cache.shared.itpearls_IteractionEdit = false
# eclipselink.cache.size.itpearls_IteractionEdit = 1000
# eclipselink.cache.size.itpearls_IteractionEdit.Edit = 200
eclipselink.cache.shared.itpearls_CandidateCV=true
eclipselink.cache.size.itpearls_CandidateCV=5000
eclipselink.cache.shared.itpearls_Iteraction=true
eclipselink.cache.size.itpearls_Iteraction=100
eclipselink.cache.shared.itpearls_Project=true
eclipselink.cache.size.itpearls_Project=200
eclipselink.cache.shared.itpearls_City=true
eclipselink.cache.size.itpearls_City=500
eclipselink.cache.shared.itpearls_Company=true
eclipselink.cache.size.itpearls_Company=3000
eclipselink.cache.shared.itpearls_CompanyDepartament=true
eclipselink.cache.size.itpearls_CompanyDepartament=500
eclipselink.cache.shared.itpearls_CompanyGroup=true
eclipselink.cache.size.itpearls_CompanyGroup=100
eclipselink.cache.shared.itpearls_Country=true
eclipselink.cache.size.itpearls_Country=100
eclipselink.cache.shared.itpearls_FileType=true
eclipselink.cache.size.itpearls_FileType=100
eclipselink.cache.shared.itpearls_JobCandidate=true
eclipselink.cache.size.itpearls_JobCandidate=5000
eclipselink.cache.shared.sec_ExtUser=true
eclipselink.cache.size.sec_User=100
# eclipselink.cache.shared.itpearls_JobHistory = true
# eclipselink.cache.size.itpearls_JobHistory = 200
eclipselink.cache.shared.itpearls_Person=true
eclipselink.cache.size.itpearls_Person=100
# eclipselink.cache.shared.itpearls_RecruitingRecrutiers = true
# eclipselink.cache.size.itpearls_RecruitingRecrutiers = 200
eclipselink.cache.shared.itpearls_RecrutiersTasks = true
eclipselink.cache.size.itpearls_RecrutiersTasks = 200
eclipselink.cache.shared.itpearls_Region=true
eclipselink.cache.size.itpearls_Region=100
eclipselink.cache.shared.itpearls_SkillTree=true
eclipselink.cache.size.itpearls_SkillTree=1000
eclipselink.cache.shared.itpearls_SocialNetworkType=true
eclipselink.cache.size.itpearls_SocialNetworkType=100
eclipselink.cache.shared.itpearls_SocialNetworkURLs=true
eclipselink.cache.size.itpearls_SocialNetworkURLs=500
eclipselink.cache.shared.itpearls_SomeFiles=true
eclipselink.cache.size.itpearls_SomeFiles=500
eclipselink.cache.shared.itpearls_SomeFilesAgreement=true
eclipselink.cache.size.itpearls_SomeFilesAgreement=500
eclipselink.cache.shared.itpearls_SomeFilesCandidateCV=true
eclipselink.cache.size.itpearls_SomeFilesCandidateCV=500
eclipselink.cache.shared.itpearls_SomeFilesOpenPosition=true
eclipselink.cache.size.itpearls_SomeFilesOpenPosition=500
eclipselink.cache.shared.itpearls_Specialisation=true
eclipselink.cache.size.itpearls_Specialisation=100
eclipselink.cache.shared.itpearls_SubscribeCandidateAction=true
eclipselink.cache.size.itpearls_SubscribeCandidateAction=100
eclipselink.cache.shared.itpearls_InternalEmailer=true
eclipselink.cache.size.itpearls_InternalEmailer=500
eclipselink.cache.shared.itpearls_InternalEmailerTemplate=true
eclipselink.cache.size.itpearls_InternalEmailerTemplate=500
eclipselink.cache.shared.itpearls_InternalEmailTemplate=true
eclipselink.cache.size.itpearls_InternalEmailTemplate=500
eclipselink.cache.shared.itpearls_InternalEmailTemplateInteraction=true
eclipselink.cache.size.itpearls_InternalEmailTemplateInteraction=500
eclipselink.cache.shared.itpearls_SignIcons=true
eclipselink.cache.size.itpearls_SignIcons=200
eclipselink.cache.shared.itpearls_SkillsFilterLastSelection=true
eclipselink.cache.size.itpearls_SkillsFilterLastSelection=500
eclipselink.cache.shared.itpearls_ApplicationRecruitment=true
eclipselink.cache.size.itpearls_ApplicationRecruitment=500
eclipselink.cache.shared.itpearls_ApplicationRecruitmentList=true
eclipselink.cache.size.itpearls_ApplicationRecruitmentList=500
eclipselink.cache.shared.itpearls_ApplicationSetup=true
eclipselink.cache.size.itpearls_ApplicationSetup=500
eclipselink.cache.shared.itpearls_LaborAgeementType=true
eclipselink.cache.size.itpearls_LaborAgeementType=200
eclipselink.cache.shared.itpearls_LaborAgreement=true
eclipselink.cache.size.itpearls_LaborAgreement=200
eclipselink.cache.shared.itpearls_OpenPositionComment=true
eclipselink.cache.size.itpearls_OpenPositionComment=1000
eclipselink.cache.shared.itpearls_OpenPositionNews=true
eclipselink.cache.size.itpearls_OpenPositionNews=1000
eclipselink.cache.shared.itpearls_OutstaffingRates=true
eclipselink.cache.size.itpearls_OutstaffingRates=500
eclipselink.cache.shared.itpearls_PersonelReserve=true
eclipselink.cache.size.itpearls_PersonelReserve=500
eclipselink.cache.shared.itpearls_Employee=true
eclipselink.cache.size.itpearls_Employee=500
eclipselink.cache.shared.itpearls_EmployeeWorkStatus=true
eclipselink.cache.size.itpearls_EmployeeWorkStatus=500
eclipselink.cache.shared.itpearls_User=true
eclipselink.cache.size.itpearls_User=500
eclipselink.cache.shared.itpearls_Grade=true
eclipselink.cache.size.itpearls_Grade=200
eclipselink.cache.shared.itpearls_JobCandidateSignIcon=true
eclipselink.cache.size.itpearls_JobCandidateSignIcon=1000
eclipselink.cache.shared.itpearls_Ownershup=true
eclipselink.cache.size.itpearls_Ownershup=200
eclipselink.cache.shared.itpearls_RecrutiesTasks=true
eclipselink.cache.size.itpearls_RecrutiesTasks=1000
eclipselink.cache.shared.itpearls_Position=true
eclipselink.cache.size.itpearls_Position=500
