alter table HUNTTECH_SKILL_TREE rename column job_candidate_id to job_candidate_id__u85242 ;
alter table HUNTTECH_SKILL_TREE drop constraint FK_HUNTTECH_SKILL_TREE_ON_JOB_CANDIDATE ;
drop index IDX_HUNTTECH_SKILL_TREE_ON_JOB_CANDIDATE ;
