alter table HUNTTECH_SKILL_TREE add constraint FK_HUNTTECH_SKILL_TREE_ON_FILE_IMAGE_LOGO foreign key (FILE_IMAGE_LOGO) references SYS_FILE(ID);
create index IDX_HUNTTECH_SKILL_TREE_ON_FILE_IMAGE_LOGO on HUNTTECH_SKILL_TREE (FILE_IMAGE_LOGO);
