alter table ITPEARLS_SKILL_TREE add constraint FK_ITPEARLS_SKILL_TREE_ON_FILE_IMAGE_LOGO foreign key (FILE_IMAGE_LOGO) references SYS_FILE(ID);
create index IDX_ITPEARLS_SKILL_TREE_ON_FILE_IMAGE_LOGO on ITPEARLS_SKILL_TREE (FILE_IMAGE_LOGO);
