alter table HUNTTECH_PROJECT add constraint FK_HUNTTECH_PROJECT_ON_PROJECT_GROUP foreign key (PROJECT_GROUP) references HUNTTECH_PROJECT(ID);
create index IDX_HUNTTECH_PROJECT_ON_PROJECT_GROUP on HUNTTECH_PROJECT (PROJECT_GROUP);
