alter table HUNTTECH_JOB_CANDIDATE rename column open_position_id to open_position_id__u58501 ;
alter table HUNTTECH_JOB_CANDIDATE drop constraint FK_HUNTTECH_JOB_CANDIDATE_ON_OPEN_POSITION ;
drop index IDX_HUNTTECH_JOB_CANDIDATE_ON_OPEN_POSITION ;
