alter table HUNTTECH_POSITION rename column job_candidate_id to job_candidate_id__u64046 ;
alter table HUNTTECH_POSITION drop constraint FK_HUNTTECH_POSITION_ON_JOB_CANDIDATE ;
drop index IDX_HUNTTECH_POSITION_ON_JOB_CANDIDATE ;
