alter table HUNTTECH_POSITION add constraint FK_HUNTTECH_POSITION_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references HUNTTECH_JOB_CANDIDATE(ID);
create index IDX_HUNTTECH_POSITION_ON_JOB_CANDIDATE on HUNTTECH_POSITION (JOB_CANDIDATE_ID);
