alter table ITPEARLS_POSITION add constraint FK_ITPEARLS_POSITION_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID);
create index IDX_ITPEARLS_POSITION_ON_JOB_CANDIDATE on ITPEARLS_POSITION (JOB_CANDIDATE_ID);
