alter table HUNTTECH_PROJECT add constraint FK_HUNTTECH_PROJECT_ON_PROJECT_TREE foreign key (PROJECT_TREE_ID) references HUNTTECH_PROJECT(ID);
create index IDX_HUNTTECH_PROJECT_ON_PROJECT_TREE on HUNTTECH_PROJECT (PROJECT_TREE_ID);
