alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_COMPANY foreign key (COMPANY_ID) references ITPEARLS_COMPANY(ID);
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_COMPANY on ITPEARLS_LABOR_AGREEMENT (COMPANY_ID);
