-- begin ITPEARLS_RECRUITING_RECRUTIERS
alter table ITPEARLS_RECRUITING_RECRUTIERS add constraint FK_ITPEARLS_RECRUITING_RECRUTIERS_ON_RECRUTIER_NAME foreign key (RECRUTIER_NAME_ID) references SEC_USER(ID)^
alter table ITPEARLS_RECRUITING_RECRUTIERS add constraint FK_ITPEARLS_RECRUITING_RECRUTIERS_ON_RECRUTIER_CV foreign key (RECRUTIER_CV_ID) references SYS_FILE(ID)^
create index IDX_ITPEARLS_RECRUITING_RECRUTIERS_ON_RECRUTIER_NAME on ITPEARLS_RECRUITING_RECRUTIERS (RECRUTIER_NAME_ID)^
create index IDX_ITPEARLS_RECRUITING_RECRUTIERS_ON_RECRUTIER_CV on ITPEARLS_RECRUITING_RECRUTIERS (RECRUTIER_CV_ID)^
-- end ITPEARLS_RECRUITING_RECRUTIERS
-- begin ITPEARLS_SOCIAL_NETWORK_UR_LS
alter table ITPEARLS_SOCIAL_NETWORK_UR_LS add constraint FK_ITPEARLS_SOCIAL_NETWORK_UR_LS_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_SOCIAL_NETWORK_UR_LS add constraint FK_ITPEARLS_SOCIAL_NETWORK_UR_LS_ON_SOCIAL_NETWORK_URL foreign key (SOCIAL_NETWORK_URL_ID) references ITPEARLS_SOCIAL_NETWORK_TYPE(ID)^
create index IDX_ITPEARLS_SOCIAL_NETWORK_UR_LS_ON_JOB_CANDIDATE on ITPEARLS_SOCIAL_NETWORK_UR_LS (JOB_CANDIDATE_ID)^
create index IDX_ITPEARLS_SOCIAL_NETWORK_UR_LS_ON_SOCIAL_NETWORK_URL on ITPEARLS_SOCIAL_NETWORK_UR_LS (SOCIAL_NETWORK_URL_ID)^
create index IDX_ITPEARLS_SOCIAL_NETWORK_U_R_LS on ITPEARLS_SOCIAL_NETWORK_UR_LS (NETWORK_URLS)^
create index IDX_NETWORK_NAME on ITPEARLS_SOCIAL_NETWORK_UR_LS (NETWORK_NAME)^
-- end ITPEARLS_SOCIAL_NETWORK_UR_LS
-- begin ITPEARLS_LABOR_AGREEMENT
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_LEGAL_ENTITY_EMPLOYEE foreign key (LEGAL_ENTITY_EMPLOYEE_ID) references ITPEARLS_COMPANY(ID)^
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_CONTRACTOR_COMPANY foreign key (CONTRACTOR_COMPANY_ID) references ITPEARLS_COMPANY(ID)^
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_ADDITIONAL_LABOR_AGREEMENT foreign key (ADDITIONAL_LABOR_AGREEMENT_ID) references ITPEARLS_LABOR_AGREEMENT(ID)^
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_LEGAL_ENTITY_FROM foreign key (LEGAL_ENTITY_FROM_ID) references ITPEARLS_COMPANY(ID)^
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_COMPANY foreign key (COMPANY_ID) references ITPEARLS_COMPANY(ID)^
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_LABOR_AGREEMENT_TYPE foreign key (LABOR_AGREEMENT_TYPE_ID) references ITPEARLS_LABOR_AGEEMENT_TYPE(ID)^
alter table ITPEARLS_LABOR_AGREEMENT add constraint FK_ITPEARLS_LABOR_AGREEMENT_ON_FILE_AGREEMENT foreign key (FILE_AGREEMENT_ID) references SYS_FILE(ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_JOB_CANDIDATE on ITPEARLS_LABOR_AGREEMENT (JOB_CANDIDATE_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_LEGAL_ENTITY_EMPLOYEE on ITPEARLS_LABOR_AGREEMENT (LEGAL_ENTITY_EMPLOYEE_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_CONTRACTOR_COMPANY on ITPEARLS_LABOR_AGREEMENT (CONTRACTOR_COMPANY_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_ADDITIONAL_LABOR_AGREEMENT on ITPEARLS_LABOR_AGREEMENT (ADDITIONAL_LABOR_AGREEMENT_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_LEGAL_ENTITY_FROM on ITPEARLS_LABOR_AGREEMENT (LEGAL_ENTITY_FROM_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_COMPANY on ITPEARLS_LABOR_AGREEMENT (COMPANY_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_LABOR_AGREEMENT_TYPE on ITPEARLS_LABOR_AGREEMENT (LABOR_AGREEMENT_TYPE_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_ON_FILE_AGREEMENT on ITPEARLS_LABOR_AGREEMENT (FILE_AGREEMENT_ID)^
create index IDX_ITPEARLS_LABOR_AGREEMENT_NAME on ITPEARLS_LABOR_AGREEMENT (AGREEMENT_NAME)^
-- end ITPEARLS_LABOR_AGREEMENT
-- begin ITPEARLS_CANDIDATE_CV
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_RESUME_POSITION foreign key (RESUME_POSITION_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_TO_VACANCY foreign key (TO_VACANCY_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_FILE_CV foreign key (FILE_CV_ID) references SYS_FILE(ID)^
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_ORIGINAL_FILE_CV foreign key (ORIGINAL_FILE_CV_ID) references SYS_FILE(ID)^
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_FILE_IMAGE_FACE foreign key (FILE_IMAGE_FACE) references SYS_FILE(ID)^
alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_CANDIDATE_CV_WORK_PLACE foreign key (CANDIDATE_CV_WORK_PLACE_ID) references ITPEARLS_CANDIDATE_CV_WORK_PLACE(ID)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_CANDIDATE on ITPEARLS_CANDIDATE_CV (CANDIDATE_ID)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_RESUME_POSITION on ITPEARLS_CANDIDATE_CV (RESUME_POSITION_ID)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_TO_VACANCY on ITPEARLS_CANDIDATE_CV (TO_VACANCY_ID)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_OWNER on ITPEARLS_CANDIDATE_CV (OWNER_ID)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_FILE_CV on ITPEARLS_CANDIDATE_CV (FILE_CV_ID)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_ORIGINAL_FILE_CV on ITPEARLS_CANDIDATE_CV (ORIGINAL_FILE_CV_ID)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_FILE_IMAGE_FACE on ITPEARLS_CANDIDATE_CV (FILE_IMAGE_FACE)^
create index IDX_ITPEARLS_CANDIDATE_CV_ON_CANDIDATE_CV_WORK_PLACE on ITPEARLS_CANDIDATE_CV (CANDIDATE_CV_WORK_PLACE_ID)^
create index IDX_ITPEARLS_CANDIDATE_C_V_DATE_POST on ITPEARLS_CANDIDATE_CV (DATE_POST)^
-- end ITPEARLS_CANDIDATE_CV
-- begin ITPEARLS_SETUP
alter table ITPEARLS_SETUP add constraint FK_ITPEARLS_SETUP_ON_PARAM_USER foreign key (PARAM_USER_ID) references SEC_USER(ID)^
create unique index IDX_ITPEARLS_SETUP_UK_PERAM_NAME on ITPEARLS_SETUP (PERAM_NAME) where DELETE_TS is null ^
create index IDX_ITPEARLS_SETUP_ON_PARAM_USER on ITPEARLS_SETUP (PARAM_USER_ID)^
-- end ITPEARLS_SETUP
-- begin ITPEARLS_REGION
alter table ITPEARLS_REGION add constraint FK_ITPEARLS_REGION_ON_REGION_COUNTRY foreign key (REGION_COUNTRY_ID) references ITPEARLS_COUNTRY(ID)^
create unique index IDX_ITPEARLS_REGION_UK_REGION_RU_NAME on ITPEARLS_REGION (REGION_RU_NAME) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_REGION_UK_REGION_CODE on ITPEARLS_REGION (REGION_CODE) where DELETE_TS is null ^
create index IDX_ITPEARLS_REGION_ON_REGION_COUNTRY on ITPEARLS_REGION (REGION_COUNTRY_ID)^
create index IDX_ITPEARLS_REGION on ITPEARLS_REGION (ID)^
-- end ITPEARLS_REGION
-- begin ITPEARLS_ITEARCTION_REQUIREMENTS
alter table ITPEARLS_ITEARCTION_REQUIREMENTS add constraint FK_ITPEARLS_ITEARCTION_REQUIREMENTS_ON_ITERACTION foreign key (ITERACTION_ID) references ITPEARLS_ITERACTION(ID)^
alter table ITPEARLS_ITEARCTION_REQUIREMENTS add constraint FK_ITPEARLS_ITEARCTION_REQUIREMENTS_ON_ITERACTION_REQUIREMEN foreign key (ITERACTION_REQUIREMEN_ID) references ITPEARLS_ITERACTION(ID)^
create index IDX_ITPEARLS_ITEARCTION_REQUIREMENTS_ON_ITERACTION on ITPEARLS_ITEARCTION_REQUIREMENTS (ITERACTION_ID)^
create index IDX_ITPEARLS_ITEARCTION_REQUIREMENTS_ON_ITERACTION_REQUIREMEN on ITPEARLS_ITEARCTION_REQUIREMENTS (ITERACTION_REQUIREMEN_ID)^
-- end ITPEARLS_ITEARCTION_REQUIREMENTS
-- begin ITPEARLS_PERSON
alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_POSITION_COUNTRY foreign key (POSITION_COUNTRY_ID) references ITPEARLS_COUNTRY(ID)^
alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_CITY_OF_RESIDENCE foreign key (CITY_OF_RESIDENCE_ID) references ITPEARLS_CITY(ID)^
alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_PERSON_POSITION foreign key (PERSON_POSITION_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_COMPANY_DEPARTMENT foreign key (COMPANY_DEPARTMENT_ID) references ITPEARLS_COMPANY_DEPARTAMENT(ID)^
alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_FILE_IMAGE_FACE foreign key (FILE_IMAGE_FACE) references SYS_FILE(ID)^
create unique index IDX_ITPEARLS_PERSON_UK_MOB_PHONE on ITPEARLS_PERSON (MOB_PHONE) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_PERSON_UK_SKYPE_NAME on ITPEARLS_PERSON (SKYPE_NAME) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_PERSON_UK_WIBER_NAME on ITPEARLS_PERSON (WIBER_NAME) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_PERSON_UK_WATSUP_NAME on ITPEARLS_PERSON (WATSUP_NAME) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_PERSON_UK_TELEGRAM_NAME on ITPEARLS_PERSON (TELEGRAM_NAME) where DELETE_TS is null ^
create index IDX_ITPEARLS_PERSON_ON_POSITION_COUNTRY on ITPEARLS_PERSON (POSITION_COUNTRY_ID)^
create index IDX_ITPEARLS_PERSON_ON_CITY_OF_RESIDENCE on ITPEARLS_PERSON (CITY_OF_RESIDENCE_ID)^
create index IDX_ITPEARLS_PERSON_ON_PERSON_POSITION on ITPEARLS_PERSON (PERSON_POSITION_ID)^
create index IDX_ITPEARLS_PERSON_ON_COMPANY_DEPARTMENT on ITPEARLS_PERSON (COMPANY_DEPARTMENT_ID)^
create index IDX_ITPEARLS_PERSON_ON_FILE_IMAGE_FACE on ITPEARLS_PERSON (FILE_IMAGE_FACE)^
create index IDX_ITPEARLS_PERSON_FIRST_NAME on ITPEARLS_PERSON (FIRST_NAME)^
create index IDX_ITPEARLS_PERSON_MIDDLE_NAME on ITPEARLS_PERSON (MIDDLE_NAME)^
create index IDX_ITPEARLS_PERSON_SECOND_NAME on ITPEARLS_PERSON (SECOND_NAME)^
-- end ITPEARLS_PERSON
-- begin ITPEARLS_CITY
alter table ITPEARLS_CITY add constraint FK_ITPEARLS_CITY_ON_CITY_REGION foreign key (CITY_REGION_ID) references ITPEARLS_REGION(ID)^
alter table ITPEARLS_CITY add constraint FK_ITPEARLS_CITY_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
create unique index IDX_ITPEARLS_CITY_UK_CITY_PHONE_CODE on ITPEARLS_CITY (CITY_PHONE_CODE) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_CITY_UK_CITY_RU_NAME on ITPEARLS_CITY (CITY_RU_NAME) where DELETE_TS is null ^
create index IDX_ITPEARLS_CITY_ON_CITY_REGION on ITPEARLS_CITY (CITY_REGION_ID)^
create index IDX_ITPEARLS_CITY_ON_OPEN_POSITION on ITPEARLS_CITY (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_CITY_RU_NAME on ITPEARLS_CITY (CITY_RU_NAME)^
-- end ITPEARLS_CITY
-- begin ITPEARLS_POSSIBLE_NAMES
alter table ITPEARLS_POSSIBLE_NAMES add constraint FK_ITPEARLS_POSSIBLE_NAMES_ON_POSITION foreign key (POSITION_ID) references ITPEARLS_POSITION(ID)^
create unique index IDX_ITPEARLS_POSSIBLE_NAMES_UK_POSSIBLE_EN_NAME_POSIION on ITPEARLS_POSSIBLE_NAMES (POSSIBLE_EN_NAME_POSIION) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_POSSIBLE_NAMES_UK_POSSIBLE_NAME on ITPEARLS_POSSIBLE_NAMES (POSSIBLE_NAME) where DELETE_TS is null ^
create index IDX_ITPEARLS_POSSIBLE_NAMES_ON_POSITION on ITPEARLS_POSSIBLE_NAMES (POSITION_ID)^
create index IDX_ITPEARLS_POSSIBLE_NAMES_EN_NAME_POSITION on ITPEARLS_POSSIBLE_NAMES (POSSIBLE_EN_NAME_POSIION)^
create index IDX_ITPEARLS_POSSIBLE_NAMES_POSSIBLE_NAME on ITPEARLS_POSSIBLE_NAMES (POSSIBLE_NAME)^
-- end ITPEARLS_POSSIBLE_NAMES
-- begin ITPEARLS_SKILL_TREE
alter table ITPEARLS_SKILL_TREE add constraint FK_ITPEARLS_SKILL_TREE_ON_SKILL_TREE foreign key (SKILL_TREE_ID) references ITPEARLS_SKILL_TREE(ID)^
alter table ITPEARLS_SKILL_TREE add constraint FK_ITPEARLS_SKILL_TREE_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_SKILL_TREE add constraint FK_ITPEARLS_SKILL_TREE_ON_CANDIDATE_CV foreign key (CANDIDATE_CV_ID) references ITPEARLS_CANDIDATE_CV(ID)^
alter table ITPEARLS_SKILL_TREE add constraint FK_ITPEARLS_SKILL_TREE_ON_SPECIALISATION foreign key (SPECIALISATION_ID) references ITPEARLS_SPECIALISATION(ID)^
alter table ITPEARLS_SKILL_TREE add constraint FK_ITPEARLS_SKILL_TREE_ON_FILE_IMAGE_LOGO foreign key (FILE_IMAGE_LOGO) references SYS_FILE(ID)^
create unique index IDX_ITPEARLS_SKILL_TREE_UK_SKILL_NAME on ITPEARLS_SKILL_TREE (SKILL_NAME) where DELETE_TS is null ^
create index IDX_ITPEARLS_SKILL_TREE_ON_SKILL_TREE on ITPEARLS_SKILL_TREE (SKILL_TREE_ID)^
create index IDX_ITPEARLS_SKILL_TREE_ON_OPEN_POSITION on ITPEARLS_SKILL_TREE (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_SKILL_TREE_ON_CANDIDATE_CV on ITPEARLS_SKILL_TREE (CANDIDATE_CV_ID)^
create index IDX_ITPEARLS_SKILL_TREE_ON_SPECIALISATION on ITPEARLS_SKILL_TREE (SPECIALISATION_ID)^
create index IDX_ITPEARLS_SKILL_TREE_ON_FILE_IMAGE_LOGO on ITPEARLS_SKILL_TREE (FILE_IMAGE_LOGO)^
create index IDX_ITPEARLS_SKILL_TREE on ITPEARLS_SKILL_TREE (SKILL_NAME)^
-- end ITPEARLS_SKILL_TREE
-- begin ITPEARLS_SPECIALISATION
create unique index IDX_ITPEARLS_SPECIALISATION_UK_SPEC_RU_NAME on ITPEARLS_SPECIALISATION (SPEC_RU_NAME) where DELETE_TS is null ^
-- end ITPEARLS_SPECIALISATION
-- begin ITPEARLS_LABOR_AGEEMENT_TYPE
create index IDX_ITPEARLS_LABOR_AGEEMENT_TYPE_NAME on ITPEARLS_LABOR_AGEEMENT_TYPE (NAME_AGREEMENT)^
-- end ITPEARLS_LABOR_AGEEMENT_TYPE
-- begin ITPEARLS_JOB_HISTORY
alter table ITPEARLS_JOB_HISTORY add constraint FK_ITPEARLS_JOB_HISTORY_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_JOB_HISTORY add constraint FK_ITPEARLS_JOB_HISTORY_ON_CURRENT_POSITION foreign key (CURRENT_POSITION_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_JOB_HISTORY add constraint FK_ITPEARLS_JOB_HISTORY_ON_CURRENT_COMPANY foreign key (CURRENT_COMPANY_ID) references ITPEARLS_COMPANY(ID)^
create index IDX_ITPEARLS_JOB_HISTORY_ON_CANDIDATE on ITPEARLS_JOB_HISTORY (CANDIDATE_ID)^
create index IDX_ITPEARLS_JOB_HISTORY_ON_CURRENT_POSITION on ITPEARLS_JOB_HISTORY (CURRENT_POSITION_ID)^
create index IDX_ITPEARLS_JOB_HISTORY_ON_CURRENT_COMPANY on ITPEARLS_JOB_HISTORY (CURRENT_COMPANY_ID)^
-- end ITPEARLS_JOB_HISTORY
-- begin ITPEARLS_SOME_FILES
alter table ITPEARLS_SOME_FILES add constraint FK_ITPEARLS_SOME_FILES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
alter table ITPEARLS_SOME_FILES add constraint FK_ITPEARLS_SOME_FILES_ON_FILE_OWNER foreign key (FILE_OWNER_ID) references SEC_USER(ID)^
alter table ITPEARLS_SOME_FILES add constraint FK_ITPEARLS_SOME_FILES_ON_FILE_TYPE foreign key (FILE_TYPE_ID) references ITPEARLS_FILE_TYPE(ID)^
alter table ITPEARLS_SOME_FILES add constraint FK_ITPEARLS_SOME_FILES_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_SOME_FILES add constraint FK_ITPEARLS_SOME_FILES_ON_CANDIDATE_CV foreign key (CANDIDATE_CV_ID) references ITPEARLS_CANDIDATE_CV(ID)^
alter table ITPEARLS_SOME_FILES add constraint FK_ITPEARLS_SOME_FILES_ON_LABOR_AGREEMENT foreign key (LABOR_AGREEMENT_ID) references ITPEARLS_LABOR_AGREEMENT(ID)^
create index IDX_ITPEARLS_SOME_FILES_ON_FILE_DESCRIPTOR on ITPEARLS_SOME_FILES (FILE_DESCRIPTOR_ID)^
create index IDX_ITPEARLS_SOME_FILES_ON_FILE_OWNER on ITPEARLS_SOME_FILES (FILE_OWNER_ID)^
create index IDX_ITPEARLS_SOME_FILES_ON_FILE_TYPE on ITPEARLS_SOME_FILES (FILE_TYPE_ID)^
create index IDX_ITPEARLS_SOME_FILES_ON_OPEN_POSITION on ITPEARLS_SOME_FILES (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_SOME_FILES_ON_CANDIDATE_CV on ITPEARLS_SOME_FILES (CANDIDATE_CV_ID)^
create index IDX_ITPEARLS_SOME_FILES_ON_LABOR_AGREEMENT on ITPEARLS_SOME_FILES (LABOR_AGREEMENT_ID)^
-- end ITPEARLS_SOME_FILES
-- begin ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION
alter table ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION add constraint FK_ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION add constraint FK_ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION_ON_SUBSCRIBER foreign key (SUBSCRIBER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION_ON_CANDIDATE on ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION (CANDIDATE_ID)^
create index IDX_ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION_ON_SUBSCRIBER on ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION (SUBSCRIBER_ID)^
-- end ITPEARLS_SUBSCRIBE_CANDIDATE_ACTION
-- begin ITPEARLS_JOB_CANDIDATE
alter table ITPEARLS_JOB_CANDIDATE add constraint FK_ITPEARLS_JOB_CANDIDATE_ON_PERSON_POSITION foreign key (PERSON_POSITION_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_JOB_CANDIDATE add constraint FK_ITPEARLS_JOB_CANDIDATE_ON_CURRENT_COMPANY foreign key (CURRENT_COMPANY_ID) references ITPEARLS_COMPANY(ID)^
alter table ITPEARLS_JOB_CANDIDATE add constraint FK_ITPEARLS_JOB_CANDIDATE_ON_CITY_OF_RESIDENCE foreign key (CITY_OF_RESIDENCE_ID) references ITPEARLS_CITY(ID)^
alter table ITPEARLS_JOB_CANDIDATE add constraint FK_ITPEARLS_JOB_CANDIDATE_ON_SPECIALISATION foreign key (SPECIALISATION_ID) references ITPEARLS_SPECIALISATION(ID)^
alter table ITPEARLS_JOB_CANDIDATE add constraint FK_ITPEARLS_JOB_CANDIDATE_ON_SKILL_TREE foreign key (SKILL_TREE_ID) references ITPEARLS_SKILL_TREE(ID)^
alter table ITPEARLS_JOB_CANDIDATE add constraint FK_ITPEARLS_JOB_CANDIDATE_ON_FILE_IMAGE_FACE foreign key (FILE_IMAGE_FACE) references SYS_FILE(ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_ON_PERSON_POSITION on ITPEARLS_JOB_CANDIDATE (PERSON_POSITION_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_ON_CURRENT_COMPANY on ITPEARLS_JOB_CANDIDATE (CURRENT_COMPANY_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_ON_CITY_OF_RESIDENCE on ITPEARLS_JOB_CANDIDATE (CITY_OF_RESIDENCE_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_ON_SPECIALISATION on ITPEARLS_JOB_CANDIDATE (SPECIALISATION_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_ON_SKILL_TREE on ITPEARLS_JOB_CANDIDATE (SKILL_TREE_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_ON_FILE_IMAGE_FACE on ITPEARLS_JOB_CANDIDATE (FILE_IMAGE_FACE)^
create index IDX_ITPEARLS_JOB_CANDIDATE_SECOND_NAME on ITPEARLS_JOB_CANDIDATE (SECOND_NAME)^
create index IDX_ITPEARLS_JOB_CANDIDATE_FULL_NAME on ITPEARLS_JOB_CANDIDATE (FULL_NAME)^
create index IDX_ITPEARLS_JOB_CANDIDATE_FIRST_NAME on ITPEARLS_JOB_CANDIDATE (FIRST_NAME)^
-- end ITPEARLS_JOB_CANDIDATE
-- begin ITPEARLS_COMPANY_DEPARTAMENT
alter table ITPEARLS_COMPANY_DEPARTAMENT add constraint FK_ITPEARLS_COMPANY_DEPARTAMENT_ON_COMPANY_NAME foreign key (COMPANY_NAME_ID) references ITPEARLS_COMPANY(ID)^
alter table ITPEARLS_COMPANY_DEPARTAMENT add constraint FK_ITPEARLS_COMPANY_DEPARTAMENT_ON_DEPARTAMENT_HR_DIRECTOR foreign key (DEPARTAMENT_HR_DIRECTOR_ID) references ITPEARLS_PERSON(ID)^
alter table ITPEARLS_COMPANY_DEPARTAMENT add constraint FK_ITPEARLS_COMPANY_DEPARTAMENT_ON_DEPARTAMENT_DIRECTOR foreign key (DEPARTAMENT_DIRECTOR_ID) references ITPEARLS_PERSON(ID)^
create index IDX_ITPEARLS_COMPANY_DEPARTAMENT_ON_COMPANY_NAME on ITPEARLS_COMPANY_DEPARTAMENT (COMPANY_NAME_ID)^
create index IDX_ITPEARLS_COMPANY_DEPARTAMENT_ON_DEPARTAMENT_HR_DIRECTOR on ITPEARLS_COMPANY_DEPARTAMENT (DEPARTAMENT_HR_DIRECTOR_ID)^
create index IDX_ITPEARLS_COMPANY_DEPARTAMENT_ON_DEPARTAMENT_DIRECTOR on ITPEARLS_COMPANY_DEPARTAMENT (DEPARTAMENT_DIRECTOR_ID)^
-- end ITPEARLS_COMPANY_DEPARTAMENT
-- begin ITPEARLS_ITERACTION_LIST
alter table ITPEARLS_ITERACTION_LIST add constraint FK_ITPEARLS_ITERACTION_LIST_ON_ITERACTION_TYPE foreign key (ITERACTION_TYPE_ID) references ITPEARLS_ITERACTION(ID)^
alter table ITPEARLS_ITERACTION_LIST add constraint FK_ITPEARLS_ITERACTION_LIST_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_ITERACTION_LIST add constraint FK_ITPEARLS_ITERACTION_LIST_ON_VACANCY foreign key (VACANCY_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_ITERACTION_LIST add constraint FK_ITPEARLS_ITERACTION_LIST_ON_RECRUTIER foreign key (RECRUTIER_ID) references SEC_USER(ID)^
alter table ITPEARLS_ITERACTION_LIST add constraint FK_ITPEARLS_ITERACTION_LIST_ON_CHAIN_INTERACTION foreign key (CHAIN_INTERACTION_ID) references ITPEARLS_ITERACTION_LIST(ID)^
create index IDX_ITPEARLS_ITERACTION_LIST_ON_ITERACTION_TYPE on ITPEARLS_ITERACTION_LIST (ITERACTION_TYPE_ID)^
create index IDX_ITPEARLS_ITERACTION_LIST_ON_CANDIDATE on ITPEARLS_ITERACTION_LIST (CANDIDATE_ID)^
create index IDX_ITPEARLS_ITERACTION_LIST_ON_VACANCY on ITPEARLS_ITERACTION_LIST (VACANCY_ID)^
create index IDX_ITPEARLS_ITERACTION_LIST_ON_RECRUTIER on ITPEARLS_ITERACTION_LIST (RECRUTIER_ID)^
create index IDX_ITPEARLS_ITERACTION_LIST_ON_CHAIN_INTERACTION on ITPEARLS_ITERACTION_LIST (CHAIN_INTERACTION_ID)^
create index IDX_ITPEARLS_ITERACTION_LIST_DATE on ITPEARLS_ITERACTION_LIST (DATE_ITERACTION)^
create index IDX_ITPEARLS_ITERACTION_LIST_NUMBER on ITPEARLS_ITERACTION_LIST (NUMBER_ITERACTION)^
-- end ITPEARLS_ITERACTION_LIST
-- begin ITPEARLS_COMPANY
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_COMPANY_OWNERSHIP foreign key (COMPANY_OWNERSHIP_ID) references ITPEARLS_OWNERSHUP(ID)^
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_COMPANY_GROUP foreign key (COMPANY_GROUP_ID) references ITPEARLS_COMPANY_GROUP(ID)^
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_COMPANY_DIRECTOR foreign key (COMPANY_DIRECTOR_ID) references ITPEARLS_PERSON(ID)^
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_CITY_OF_COMPANY foreign key (CITY_OF_COMPANY_ID) references ITPEARLS_CITY(ID)^
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_REGION_OF_COMPANY foreign key (REGION_OF_COMPANY_ID) references ITPEARLS_REGION(ID)^
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_COUNTRY_OF_COMPANY foreign key (COUNTRY_OF_COMPANY_ID) references ITPEARLS_COUNTRY(ID)^
alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_FILE_COMPANY_LOGO foreign key (FILE_COMPANY_LOGO) references SYS_FILE(ID)^
create index IDX_ITPEARLS_COMPANY_ON_COMPANY_OWNERSHIP on ITPEARLS_COMPANY (COMPANY_OWNERSHIP_ID)^
create index IDX_ITPEARLS_COMPANY_ON_COMPANY_GROUP on ITPEARLS_COMPANY (COMPANY_GROUP_ID)^
create index IDX_ITPEARLS_COMPANY_ON_COMPANY_DIRECTOR on ITPEARLS_COMPANY (COMPANY_DIRECTOR_ID)^
create index IDX_ITPEARLS_COMPANY_ON_CITY_OF_COMPANY on ITPEARLS_COMPANY (CITY_OF_COMPANY_ID)^
create index IDX_ITPEARLS_COMPANY_ON_REGION_OF_COMPANY on ITPEARLS_COMPANY (REGION_OF_COMPANY_ID)^
create index IDX_ITPEARLS_COMPANY_ON_COUNTRY_OF_COMPANY on ITPEARLS_COMPANY (COUNTRY_OF_COMPANY_ID)^
create index IDX_ITPEARLS_COMPANY_ON_FILE_COMPANY_LOGO on ITPEARLS_COMPANY (FILE_COMPANY_LOGO)^
create index IDX_COMPANY_NAME on ITPEARLS_COMPANY (COMANY_NAME)^
create index IDX_ITPEARLS_COMPANY_SHORT_NAME on ITPEARLS_COMPANY (COMPANY_SHORT_NAME)^
-- end ITPEARLS_COMPANY
-- begin ITPEARLS_ITERACTION
alter table ITPEARLS_ITERACTION add constraint FK_ITPEARLS_ITERACTION_ON_ITERACTION_TREE foreign key (ITERACTION_TREE_ID) references ITPEARLS_ITERACTION(ID)^
alter table ITPEARLS_ITERACTION add constraint FK_ITPEARLS_ITERACTION_ON_WORK_STATUS foreign key (WORK_STATUS_ID) references ITPEARLS_EMPLOYEE_WORK_STATUS(ID)^
create unique index IDX_ITPEARLS_ITERACTION_UK_ITERATION_NAME on ITPEARLS_ITERACTION (ITERATION_NAME) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_ITERACTION_UK_SIGN_PUT_RESONAL on ITPEARLS_ITERACTION (SIGN_PUT_RESONAL) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_ITERACTION_UK_SIGN_PERSONAL_RESERVE_REMOVE on ITPEARLS_ITERACTION (SIGN_PERSONAL_RESERVE_REMOVE) where DELETE_TS is null ^
create index IDX_ITPEARLS_ITERACTION_ON_ITERACTION_TREE on ITPEARLS_ITERACTION (ITERACTION_TREE_ID)^
create index IDX_ITPEARLS_ITERACTION_ON_WORK_STATUS on ITPEARLS_ITERACTION (WORK_STATUS_ID)^
create index IDX_ITPEARLS_ITERACTION_NUMBER on ITPEARLS_ITERACTION (NUMBER_)^
-- end ITPEARLS_ITERACTION
-- begin ITPEARLS_COUNTRY
create unique index IDX_ITPEARLS_COUNTRY_UK_COUNTRY_RU_NAME on ITPEARLS_COUNTRY (COUNTRY_RU_NAME) where DELETE_TS is null ^
create index IDX_COUNTRY_COUNTRY_RU_NAME on ITPEARLS_COUNTRY (COUNTRY_RU_NAME)^
-- end ITPEARLS_COUNTRY
-- begin ITPEARLS_PROJECT
alter table ITPEARLS_PROJECT add constraint FK_ITPEARLS_PROJECT_ON_PROJECT_LOGO foreign key (PROJECT_LOGO_ID) references SYS_FILE(ID)^
alter table ITPEARLS_PROJECT add constraint FK_ITPEARLS_PROJECT_ON_PROJECT_TREE foreign key (PROJECT_TREE_ID) references ITPEARLS_PROJECT(ID)^
alter table ITPEARLS_PROJECT add constraint FK_ITPEARLS_PROJECT_ON_PROJECT_DEPARTMENT foreign key (PROJECT_DEPARTMENT_ID) references ITPEARLS_COMPANY_DEPARTAMENT(ID)^
alter table ITPEARLS_PROJECT add constraint FK_ITPEARLS_PROJECT_ON_PROJECT_OWNER foreign key (PROJECT_OWNER_ID) references ITPEARLS_PERSON(ID)^
create index IDX_ITPEARLS_PROJECT_ON_PROJECT_LOGO on ITPEARLS_PROJECT (PROJECT_LOGO_ID)^
create index IDX_ITPEARLS_PROJECT_ON_PROJECT_TREE on ITPEARLS_PROJECT (PROJECT_TREE_ID)^
create index IDX_ITPEARLS_PROJECT_ON_PROJECT_DEPARTMENT on ITPEARLS_PROJECT (PROJECT_DEPARTMENT_ID)^
create index IDX_ITPEARLS_PROJECT_ON_PROJECT_OWNER on ITPEARLS_PROJECT (PROJECT_OWNER_ID)^
create index IDX_ITPEARLS_PROJECT_PROJECT_NAME on ITPEARLS_PROJECT (PROJECT_NAME)^
-- end ITPEARLS_PROJECT
-- begin ITPEARLS_POSITION
alter table ITPEARLS_POSITION add constraint FK_ITPEARLS_POSITION_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
create unique index IDX_ITPEARLS_POSITION_UK_POSITION_RU_NAME on ITPEARLS_POSITION (POSITION_RU_NAME) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_POSITION_UK_POSITION_EN_NAME on ITPEARLS_POSITION (POSITION_EN_NAME) where DELETE_TS is null ^
create index IDX_ITPEARLS_POSITION_ON_JOB_CANDIDATE on ITPEARLS_POSITION (JOB_CANDIDATE_ID)^
create index IDX_ITPEARLS_POSITION_EN_NAME on ITPEARLS_POSITION (POSITION_EN_NAME)^
create index IDX_ITPEARLS_POSITION_RU_NAME on ITPEARLS_POSITION (POSITION_RU_NAME)^
-- end ITPEARLS_POSITION
-- begin ITPEARLS_OWNERSHUP
create unique index IDX_ITPEARLS_OWNERSHUP_UK_LONG_TYPE on ITPEARLS_OWNERSHUP (LONG_TYPE) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_OWNERSHUP_UK_SHORT_TYPE on ITPEARLS_OWNERSHUP (SHORT_TYPE) where DELETE_TS is null ^
-- end ITPEARLS_OWNERSHUP
-- begin ITPEARLS_SOCIAL_NETWORK_TYPE
alter table ITPEARLS_SOCIAL_NETWORK_TYPE add constraint FK_ITPEARLS_SOCIAL_NETWORK_TYPE_ON_LOGO foreign key (LOGO_ID) references SYS_FILE(ID)^
create index IDX_ITPEARLS_SOCIAL_NETWORK_TYPE_ON_LOGO on ITPEARLS_SOCIAL_NETWORK_TYPE (LOGO_ID)^
create index IDX_ITPEARLS_SOCIAL_NETWORK_TYPE_SOCIAL_NETWORK on ITPEARLS_SOCIAL_NETWORK_TYPE (SOCIAL_NETWORK)^
-- end ITPEARLS_SOCIAL_NETWORK_TYPE
-- begin ITPEARLS_COMPANY_GROUP
create unique index IDX_ITPEARLS_COMPANY_GROUP_UK_COMPANY_RU_GROUP_NAME on ITPEARLS_COMPANY_GROUP (COMPANY_RU_GROUP_NAME) where DELETE_TS is null ^
create index IDX_ITPEARLS_COMPANY_GROUP_RU_NAME on ITPEARLS_COMPANY_GROUP (COMPANY_RU_GROUP_NAME)^
-- end ITPEARLS_COMPANY_GROUP
-- begin ITPEARLS_JOB_CANDIDATE_POSITION_LISTS
alter table ITPEARLS_JOB_CANDIDATE_POSITION_LISTS add constraint FK_ITPEARLS_JOB_CANDIDATE_POSITION_LISTS_ON_POSITION_LIST foreign key (POSITION_LIST_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_JOB_CANDIDATE_POSITION_LISTS add constraint FK_ITPEARLS_JOB_CANDIDATE_POSITION_LISTS_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_POSITION_LISTS_ON_POSITION_LIST on ITPEARLS_JOB_CANDIDATE_POSITION_LISTS (POSITION_LIST_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_POSITION_LISTS_ON_JOB_CANDIDATE on ITPEARLS_JOB_CANDIDATE_POSITION_LISTS (JOB_CANDIDATE_ID)^
-- end ITPEARLS_JOB_CANDIDATE_POSITION_LISTS
-- begin ITPEARLS_OPEN_POSITION
alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_GRADE foreign key (GRADE_ID) references ITPEARLS_GRADE(ID)^
alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_CITY_POSITION foreign key (CITY_POSITION_ID) references ITPEARLS_CITY(ID)^
alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_POSITION_TYPE foreign key (POSITION_TYPE_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_PROJECT_NAME foreign key (PROJECT_NAME_ID) references ITPEARLS_PROJECT(ID)^
alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_PARENT_OPEN_POSITION foreign key (PARENT_OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_OPEN_POSITION add constraint FK_ITPEARLS_OPEN_POSITION_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_OPEN_POSITION_ON_GRADE on ITPEARLS_OPEN_POSITION (GRADE_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_ON_CITY_POSITION on ITPEARLS_OPEN_POSITION (CITY_POSITION_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_ON_POSITION_TYPE on ITPEARLS_OPEN_POSITION (POSITION_TYPE_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_ON_PROJECT_NAME on ITPEARLS_OPEN_POSITION (PROJECT_NAME_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_ON_PARENT_OPEN_POSITION on ITPEARLS_OPEN_POSITION (PARENT_OPEN_POSITION_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_ON_OWNER on ITPEARLS_OPEN_POSITION (OWNER_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_PRIORITY on ITPEARLS_OPEN_POSITION (PRIORITY)^
create index IDX_ITPEARLS_OPEN_POSITION_VACANSY_NAME on ITPEARLS_OPEN_POSITION (VACANSY_NAME)^
create index IDX_ITPEARLS_OPEN_POSITION_OPEN_CLOSE on ITPEARLS_OPEN_POSITION (OPEN_CLOSE)^
-- end ITPEARLS_OPEN_POSITION
-- begin ITPEARLS_RECRUTIES_TASKS
alter table ITPEARLS_RECRUTIES_TASKS add constraint FK_ITPEARLS_RECRUTIES_TASKS_ON_REACRUTIER foreign key (REACRUTIER_ID) references SEC_USER(ID)^
alter table ITPEARLS_RECRUTIES_TASKS add constraint FK_ITPEARLS_RECRUTIES_TASKS_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
create index IDX_ITPEARLS_RECRUTIES_TASKS_ON_REACRUTIER on ITPEARLS_RECRUTIES_TASKS (REACRUTIER_ID)^
create index IDX_ITPEARLS_RECRUTIES_TASKS_ON_OPEN_POSITION on ITPEARLS_RECRUTIES_TASKS (OPEN_POSITION_ID)^
-- end ITPEARLS_RECRUTIES_TASKS
-- begin ITPEARLS_OPEN_POSITION_LABOR_AGREEMENT_LINK
alter table ITPEARLS_OPEN_POSITION_LABOR_AGREEMENT_LINK add constraint FK_OPEPOSLABAGR_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_OPEN_POSITION_LABOR_AGREEMENT_LINK add constraint FK_OPEPOSLABAGR_ON_LABOR_AGREEMENT foreign key (LABOR_AGREEMENT_ID) references ITPEARLS_LABOR_AGREEMENT(ID)^
-- end ITPEARLS_OPEN_POSITION_LABOR_AGREEMENT_LINK
-- begin ITPEARLS_OPEN_POSITION_RECRUTIES_TASKS_LINK
alter table ITPEARLS_OPEN_POSITION_RECRUTIES_TASKS_LINK add constraint FK_OPEPOSRECTAS_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_OPEN_POSITION_RECRUTIES_TASKS_LINK add constraint FK_OPEPOSRECTAS_ON_RECRUTIES_TASKS foreign key (RECRUTIES_TASKS_ID) references ITPEARLS_RECRUTIES_TASKS(ID)^
-- end ITPEARLS_OPEN_POSITION_RECRUTIES_TASKS_LINK
-- begin ITPEARLS_OPEN_POSITION_NEWS
alter table ITPEARLS_OPEN_POSITION_NEWS add constraint FK_ITPEARLS_OPEN_POSITION_NEWS_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_OPEN_POSITION_NEWS add constraint FK_ITPEARLS_OPEN_POSITION_NEWS_ON_CANDIDATES foreign key (CANDIDATES_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_OPEN_POSITION_NEWS add constraint FK_ITPEARLS_OPEN_POSITION_NEWS_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_OPEN_POSITION_NEWS_ON_OPEN_POSITION on ITPEARLS_OPEN_POSITION_NEWS (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_NEWS_ON_CANDIDATES on ITPEARLS_OPEN_POSITION_NEWS (CANDIDATES_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_NEWS_ON_AUTHOR on ITPEARLS_OPEN_POSITION_NEWS (AUTHOR_ID)^
-- end ITPEARLS_OPEN_POSITION_NEWS
-- begin ITPEARLS_INTERVIEW
alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_CANDIDATE foreign key (CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_CANDIDATE_CV foreign key (CANDIDATE_CV_ID) references ITPEARLS_CANDIDATE_CV(ID)^
alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_RECRUTIER foreign key (RECRUTIER_ID) references SEC_USER(ID)^
alter table ITPEARLS_INTERVIEW add constraint FK_ITPEARLS_INTERVIEW_ON_RESEARCHER foreign key (RESEARCHER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_INTERVIEW_ON_CANDIDATE on ITPEARLS_INTERVIEW (CANDIDATE_ID)^
create index IDX_ITPEARLS_INTERVIEW_ON_CANDIDATE_CV on ITPEARLS_INTERVIEW (CANDIDATE_CV_ID)^
create index IDX_ITPEARLS_INTERVIEW_ON_RECRUTIER on ITPEARLS_INTERVIEW (RECRUTIER_ID)^
create index IDX_ITPEARLS_INTERVIEW_ON_RESEARCHER on ITPEARLS_INTERVIEW (RESEARCHER_ID)^
-- end ITPEARLS_INTERVIEW
-- begin ITPEARLS_INTERVIEW_OPEN_POSITION_LINK
alter table ITPEARLS_INTERVIEW_OPEN_POSITION_LINK add constraint FK_INTOPEPOS_ON_INTERVIEW foreign key (INTERVIEW_ID) references ITPEARLS_INTERVIEW(ID)^
alter table ITPEARLS_INTERVIEW_OPEN_POSITION_LINK add constraint FK_INTOPEPOS_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
-- end ITPEARLS_INTERVIEW_OPEN_POSITION_LINK

-- begin ITPEARLS_STAFFING_TABLE
alter table ITPEARLS_STAFFING_TABLE add constraint FK_ITPEARLS_STAFFING_TABLE_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_STAFFING_TABLE add constraint FK_ITPEARLS_STAFFING_TABLE_ON_GRADE foreign key (GRADE_ID) references ITPEARLS_GRADE(ID)^
create index IDX_ITPEARLS_STAFFING_TABLE_ON_OPEN_POSITION on ITPEARLS_STAFFING_TABLE (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_STAFFING_TABLE_ON_GRADE on ITPEARLS_STAFFING_TABLE (GRADE_ID)^
-- end ITPEARLS_STAFFING_TABLE
-- begin ITPEARLS_GRADE
create unique index IDX_ITPEARLS_GRADE_UK_GRADE_NAME on ITPEARLS_GRADE (GRADE_NAME) where DELETE_TS is null ^
-- end ITPEARLS_GRADE
-- begin ITPEARLS_STAFF_CURRENT
alter table ITPEARLS_STAFF_CURRENT add constraint FK_ITPEARLS_STAFF_CURRENT_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_STAFF_CURRENT add constraint FK_ITPEARLS_STAFF_CURRENT_ON_STAFFING_TABLE foreign key (STAFFING_TABLE_ID) references ITPEARLS_STAFFING_TABLE(ID)^
create index IDX_ITPEARLS_STAFF_CURRENT_ON_EMPLOYEE on ITPEARLS_STAFF_CURRENT (EMPLOYEE_ID)^
create index IDX_ITPEARLS_STAFF_CURRENT_ON_STAFFING_TABLE on ITPEARLS_STAFF_CURRENT (STAFFING_TABLE_ID)^
-- end ITPEARLS_STAFF_CURRENT
-- begin ITPEARLS_APPLICATION_RECRUITMENT
alter table ITPEARLS_APPLICATION_RECRUITMENT add constraint FK_ITPEARLS_APPLICATION_RECRUITMENT_ON_STAFFING_TABLE foreign key (STAFFING_TABLE_ID) references ITPEARLS_STAFFING_TABLE(ID)^
alter table ITPEARLS_APPLICATION_RECRUITMENT add constraint FK_ITPEARLS_APPLICATRECRUITM_ON_APPLICATION_RECRUITMENT_LIST foreign key (APPLICATION_RECRUITMENT_LIST_ID) references ITPEARLS_APPLICATION_RECRUITMENT_LIST(ID)^
create unique index IDX_ITPEARLS_APPLICATION_RECRUITMENT_UK_CODE on ITPEARLS_APPLICATION_RECRUITMENT (CODE) where DELETE_TS is null ^
create index IDX_ITPEARLS_APPLICATION_RECRUITMENT_ON_STAFFING_TABLE on ITPEARLS_APPLICATION_RECRUITMENT (STAFFING_TABLE_ID)^
create index IDX_ITPEARLS_APPLICARECRUIT_ON_APPLICATION_RECRUITMENT_LIST on ITPEARLS_APPLICATION_RECRUITMENT (APPLICATION_RECRUITMENT_LIST_ID)^
-- end ITPEARLS_APPLICATION_RECRUITMENT
-- begin ITPEARLS_APPLICATION_RECRUITMENT_LIST
alter table ITPEARLS_APPLICATION_RECRUITMENT_LIST add constraint FK_ITPEARLS_APPLICATION_RECRUITMENT_LIST_ON_PROJECT foreign key (PROJECT_ID) references ITPEARLS_PROJECT(ID)^
alter table ITPEARLS_APPLICATION_RECRUITMENT_LIST add constraint FK_ITPEARLS_APPLICATION_RECRUITMENT_LIST_ON_PROJECT_DEPARTMENT foreign key (PROJECT_DEPARTMENT_ID) references ITPEARLS_COMPANY_DEPARTAMENT(ID)^
alter table ITPEARLS_APPLICATION_RECRUITMENT_LIST add constraint FK_ITPEARLS_APPLICATION_RECRUITMENT_LIST_ON_COMPANY foreign key (COMPANY_ID) references ITPEARLS_COMPANY(ID)^
alter table ITPEARLS_APPLICATION_RECRUITMENT_LIST add constraint FK_ITPEARLS_APPLICATION_RECRUITMENT_LIST_ON_RECRUITER foreign key (RECRUITER_ID) references SEC_USER(ID)^
create unique index IDX_ITPEARLS_APPLICATION_RECRUITMENT_LIST_UK_QUICK_DESCRIPTION on ITPEARLS_APPLICATION_RECRUITMENT_LIST (QUICK_DESCRIPTION) where DELETE_TS is null ^
create index IDX_ITPEARLS_APPLICATION_RECRUITMENT_LIST_ON_PROJECT on ITPEARLS_APPLICATION_RECRUITMENT_LIST (PROJECT_ID)^
create index IDX_ITPEARLS_APPLICARECRUITLIST_ON_PROJECT_DEPARTMENT1 on ITPEARLS_APPLICATION_RECRUITMENT_LIST (PROJECT_DEPARTMENT_ID)^
create index IDX_ITPEARLS_APPLICATION_RECRUITMENT_LIST_ON_COMPANY on ITPEARLS_APPLICATION_RECRUITMENT_LIST (COMPANY_ID)^
create index IDX_ITPEARLS_APPLICATION_RECRUITMENT_LIST_ON_RECRUITER on ITPEARLS_APPLICATION_RECRUITMENT_LIST (RECRUITER_ID)^
-- end ITPEARLS_APPLICATION_RECRUITMENT_LIST
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create index IDX_SEC_USER_ON_IMAGE on SEC_USER (IMAGE_ID)^
-- end SEC_USER
-- begin ITPEARLS_PERSONEL_RESERVE
alter table ITPEARLS_PERSONEL_RESERVE add constraint FK_ITPEARLS_PERSONEL_RESERVE_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_PERSONEL_RESERVE add constraint FK_ITPEARLS_PERSONEL_RESERVE_ON_REACTUTIER foreign key (REACTUTIER_ID) references SEC_USER(ID)^
alter table ITPEARLS_PERSONEL_RESERVE add constraint FK_ITPEARLS_PERSONEL_RESERVE_ON_PERSON_POSITION foreign key (PERSON_POSITION_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_PERSONEL_RESERVE add constraint FK_ITPEARLS_PERSONEL_RESERVE_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
create index IDX_ITPEARLS_PERSONEL_RESERVE_ON_JOB_CANDIDATE on ITPEARLS_PERSONEL_RESERVE (JOB_CANDIDATE_ID)^
create index IDX_ITPEARLS_PERSONEL_RESERVE_ON_REACTUTIER on ITPEARLS_PERSONEL_RESERVE (REACTUTIER_ID)^
create index IDX_ITPEARLS_PERSONEL_RESERVE_ON_PERSON_POSITION on ITPEARLS_PERSONEL_RESERVE (PERSON_POSITION_ID)^
create index IDX_ITPEARLS_PERSONEL_RESERVE_ON_OPEN_POSITION on ITPEARLS_PERSONEL_RESERVE (OPEN_POSITION_ID)^
-- end ITPEARLS_PERSONEL_RESERVE
-- begin ITPEARLS_SKILLS_FILTER_LAST_SELECTION
alter table ITPEARLS_SKILLS_FILTER_LAST_SELECTION add constraint FK_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_POSITION foreign key (POSITION_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_SKILLS_FILTER_LAST_SELECTION add constraint FK_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_CITY foreign key (CITY_ID) references ITPEARLS_CITY(ID)^
alter table ITPEARLS_SKILLS_FILTER_LAST_SELECTION add constraint FK_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_SKILLS_FILTER_LAST_SELECTION add constraint FK_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_JOB_CANDIDATES foreign key (JOB_CANDIDATES_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_SKILLS_FILTER_LAST_SELECTION add constraint FK_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_POSITION on ITPEARLS_SKILLS_FILTER_LAST_SELECTION (POSITION_ID)^
create index IDX_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_CITY on ITPEARLS_SKILLS_FILTER_LAST_SELECTION (CITY_ID)^
create index IDX_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_OPEN_POSITION on ITPEARLS_SKILLS_FILTER_LAST_SELECTION (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_JOB_CANDIDATES on ITPEARLS_SKILLS_FILTER_LAST_SELECTION (JOB_CANDIDATES_ID)^
create index IDX_ITPEARLS_SKILLS_FILTER_LAST_SELECTION_ON_USER on ITPEARLS_SKILLS_FILTER_LAST_SELECTION (USER_ID)^
-- end ITPEARLS_SKILLS_FILTER_LAST_SELECTION
-- begin ITPEARLS_INTERNAL_EMAIL_TEMPLATE
alter table ITPEARLS_INTERNAL_EMAIL_TEMPLATE add constraint FK_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_TEMPLATE_OPEN_POSITION foreign key (TEMPLATE_OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_INTERNAL_EMAIL_TEMPLATE add constraint FK_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_TEMPLATE_POSITION foreign key (TEMPLATE_POSITION_ID) references ITPEARLS_POSITION(ID)^
alter table ITPEARLS_INTERNAL_EMAIL_TEMPLATE add constraint FK_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_TEMPLATE_AUTHOR foreign key (TEMPLATE_AUTHOR_ID) references SEC_USER(ID)^
alter table ITPEARLS_INTERNAL_EMAIL_TEMPLATE add constraint FK_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_INTERACTION foreign key (INTERACTION_ID) references ITPEARLS_ITERACTION(ID)^
create index IDX_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_TEMPLATE_OPEN_POSITION on ITPEARLS_INTERNAL_EMAIL_TEMPLATE (TEMPLATE_OPEN_POSITION_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_TEMPLATE_POSITION on ITPEARLS_INTERNAL_EMAIL_TEMPLATE (TEMPLATE_POSITION_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_TEMPLATE_AUTHOR on ITPEARLS_INTERNAL_EMAIL_TEMPLATE (TEMPLATE_AUTHOR_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_ON_INTERACTION on ITPEARLS_INTERNAL_EMAIL_TEMPLATE (INTERACTION_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_POSITION on ITPEARLS_INTERNAL_EMAIL_TEMPLATE (TEMPLATE_POSITION_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_AUTHOR on ITPEARLS_INTERNAL_EMAIL_TEMPLATE (TEMPLATE_AUTHOR_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAIL_TEMPLATE_OPEN_POSITION on ITPEARLS_INTERNAL_EMAIL_TEMPLATE (TEMPLATE_OPEN_POSITION_ID)^
-- end ITPEARLS_INTERNAL_EMAIL_TEMPLATE
-- begin ITPEARLS_INTERNAL_EMAILER
alter table ITPEARLS_INTERNAL_EMAILER add constraint FK_ITPEARLS_INTERNAL_EMAILER_ON_FROM_EMAIL foreign key (FROM_EMAIL_ID) references SEC_USER(ID)^
alter table ITPEARLS_INTERNAL_EMAILER add constraint FK_ITPEARLS_INTERNAL_EMAILER_ON_TO_EMAIL foreign key (TO_EMAIL_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_INTERNAL_EMAILER add constraint FK_ITPEARLS_INTERNAL_EMAILER_ON_REPLY_INTERNAL_EMAILER foreign key (REPLY_INTERNAL_EMAILER_ID) references ITPEARLS_INTERNAL_EMAILER(ID)^
alter table ITPEARLS_INTERNAL_EMAILER add constraint FK_ITPEARLS_INTERNAL_EMAILER_ON_EMAIL_TEMPLATE foreign key (EMAIL_TEMPLATE_ID) references ITPEARLS_INTERNAL_EMAIL_TEMPLATE(ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_ON_FROM_EMAIL on ITPEARLS_INTERNAL_EMAILER (FROM_EMAIL_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_ON_TO_EMAIL on ITPEARLS_INTERNAL_EMAILER (TO_EMAIL_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_ON_REPLY_INTERNAL_EMAILER on ITPEARLS_INTERNAL_EMAILER (REPLY_INTERNAL_EMAILER_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_ON_EMAIL_TEMPLATE on ITPEARLS_INTERNAL_EMAILER (EMAIL_TEMPLATE_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_REPLY_INTERNAL_EMAILER on ITPEARLS_INTERNAL_EMAILER (REPLY_INTERNAL_EMAILER_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_TO_EMAIL on ITPEARLS_INTERNAL_EMAILER (TO_EMAIL_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_EMAIL_TEMPLATE on ITPEARLS_INTERNAL_EMAILER (EMAIL_TEMPLATE_ID)^
create index IDX_ITPEARLS_INTERNAL_EMAILER_FROM_EMAIL on ITPEARLS_INTERNAL_EMAILER (FROM_EMAIL_ID)^
-- end ITPEARLS_INTERNAL_EMAILER
-- begin ITPEARLS_USER_SETTINGS
alter table ITPEARLS_USER_SETTINGS add constraint FK_ITPEARLS_USER_SETTINGS_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table ITPEARLS_USER_SETTINGS add constraint FK_ITPEARLS_USER_SETTINGS_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create unique index IDX_ITPEARLS_USER_SETTINGS_UK_USER_ID on ITPEARLS_USER_SETTINGS (USER_ID) where DELETE_TS is null ^
create index IDX_ITPEARLS_USER_SETTINGS_ON_USER on ITPEARLS_USER_SETTINGS (USER_ID)^
create index IDX_ITPEARLS_USER_SETTINGS_ON_IMAGE on ITPEARLS_USER_SETTINGS (IMAGE_ID)^
-- end ITPEARLS_USER_SETTINGS
-- begin ITPEARLS_OUTSTAFFING_RATES
alter table ITPEARLS_OUTSTAFFING_RATES add constraint FK_ITPEARLS_OUTSTAFFING_RATES_ON_CURRENCY foreign key (CURRENCY_ID) references ITPEARLS_CURRENCY(ID)^
create index IDX_ITPEARLS_OUTSTAFFING_RATES_ON_CURRENCY on ITPEARLS_OUTSTAFFING_RATES (CURRENCY_ID)^
-- end ITPEARLS_OUTSTAFFING_RATES
-- begin ITPEARLS_CURRENCY
create unique index IDX_ITPEARLS_CURRENCY_UK_CURRENCY_LONG_NAME on ITPEARLS_CURRENCY (CURRENCY_LONG_NAME) where DELETE_TS is null ^
create unique index IDX_ITPEARLS_CURRENCY_UK_CURRENCY_SHORT_NAME on ITPEARLS_CURRENCY (CURRENCY_SHORT_NAME) where DELETE_TS is null ^
-- end ITPEARLS_CURRENCY
-- begin ITPEARLS_OPEN_POSITION_COMMENT
alter table ITPEARLS_OPEN_POSITION_COMMENT add constraint FK_ITPEARLS_OPEN_POSITION_COMMENT_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_OPEN_POSITION_COMMENT add constraint FK_ITPEARLS_OPEN_POSITION_COMMENT_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_OPEN_POSITION_COMMENT_ON_OPEN_POSITION on ITPEARLS_OPEN_POSITION_COMMENT (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_OPEN_POSITION_COMMENT_ON_USER on ITPEARLS_OPEN_POSITION_COMMENT (USER_ID)^
-- end ITPEARLS_OPEN_POSITION_COMMENT
-- begin ITPEARLS_EMPLOYEE
alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_CURRENCY foreign key (CURRENCY_ID) references ITPEARLS_CURRENCY(ID)^
alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_LABOR_AGREEMENT foreign key (LABOR_AGREEMENT_ID) references ITPEARLS_LABOR_AGREEMENT(ID)^
alter table ITPEARLS_EMPLOYEE add constraint FK_ITPEARLS_EMPLOYEE_ON_WORK_STATUS foreign key (WORK_STATUS_ID) references ITPEARLS_EMPLOYEE_WORK_STATUS(ID)^
create index IDX_ITPEARLS_EMPLOYEE_ON_JOB_CANDIDATE on ITPEARLS_EMPLOYEE (JOB_CANDIDATE_ID)^
create index IDX_ITPEARLS_EMPLOYEE_ON_OPEN_POSITION on ITPEARLS_EMPLOYEE (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_EMPLOYEE_ON_CURRENCY on ITPEARLS_EMPLOYEE (CURRENCY_ID)^
create index IDX_ITPEARLS_EMPLOYEE_ON_LABOR_AGREEMENT on ITPEARLS_EMPLOYEE (LABOR_AGREEMENT_ID)^
create index IDX_ITPEARLS_EMPLOYEE_ON_WORK_STATUS on ITPEARLS_EMPLOYEE (WORK_STATUS_ID)^
-- end ITPEARLS_EMPLOYEE
-- begin ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE
alter table ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE add constraint FK_ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE add constraint FK_ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_OPEN_POSITION(ID)^
alter table ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE add constraint FK_ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE_ON_JOB_CANDIDATE on ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE (JOB_CANDIDATE_ID)^
create index IDX_ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE_ON_OPEN_POSITION on ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE (OPEN_POSITION_ID)^
create index IDX_ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE_ON_USER on ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE (USER_ID)^
-- end ITPEARLS_MY_ACTIVE_CANDIDATE_EXCLUDE
-- begin ITPEARLS_SIGN_ICONS
alter table ITPEARLS_SIGN_ICONS add constraint FK_ITPEARLS_SIGN_ICONS_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_SIGN_ICONS_ON_USER on ITPEARLS_SIGN_ICONS (USER_ID)^
-- end ITPEARLS_SIGN_ICONS
-- begin ITPEARLS_JOB_CANDIDATE_SIGN_ICON
alter table ITPEARLS_JOB_CANDIDATE_SIGN_ICON add constraint FK_ITPEARLS_JOB_CANDIDATE_SIGN_ICON_ON_JOB_CANDIDATE foreign key (JOB_CANDIDATE_ID) references ITPEARLS_JOB_CANDIDATE(ID)^
alter table ITPEARLS_JOB_CANDIDATE_SIGN_ICON add constraint FK_ITPEARLS_JOB_CANDIDATE_SIGN_ICON_ON_SIGN_ICON foreign key (SIGN_ICON_ID) references ITPEARLS_SIGN_ICONS(ID)^
alter table ITPEARLS_JOB_CANDIDATE_SIGN_ICON add constraint FK_ITPEARLS_JOB_CANDIDATE_SIGN_ICON_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_SIGN_ICON_ON_JOB_CANDIDATE on ITPEARLS_JOB_CANDIDATE_SIGN_ICON (JOB_CANDIDATE_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_SIGN_ICON_ON_SIGN_ICON on ITPEARLS_JOB_CANDIDATE_SIGN_ICON (SIGN_ICON_ID)^
create index IDX_ITPEARLS_JOB_CANDIDATE_SIGN_ICON_ON_USER on ITPEARLS_JOB_CANDIDATE_SIGN_ICON (USER_ID)^
-- end ITPEARLS_JOB_CANDIDATE_SIGN_ICON
-- begin ITPEARLS_APPLICATION_SETUP
alter table ITPEARLS_APPLICATION_SETUP add constraint FK_ITPEARLS_APPLICATION_SETUP_ON_APPLICATION_LOGO foreign key (APPLICATION_LOGO_ID) references SYS_FILE(ID)^
alter table ITPEARLS_APPLICATION_SETUP add constraint FK_ITPEARLS_APPLICATION_SETUP_ON_APPLICATION_ICON foreign key (APPLICATION_ICON_ID) references SYS_FILE(ID)^
alter table ITPEARLS_APPLICATION_SETUP add constraint FK_ITPEARLS_APPLICATION_SETUP_ON_COORDINATOR foreign key (COORDINATOR_ID) references SEC_USER(ID)^
alter table ITPEARLS_APPLICATION_SETUP add constraint FK_ITPEARLS_APPLICATION_SETUP_ON_ADMINISTRATOR foreign key (ADMINISTRATOR_ID) references SEC_USER(ID)^
create index IDX_ITPEARLS_APPLICATION_SETUP_ON_APPLICATION_LOGO on ITPEARLS_APPLICATION_SETUP (APPLICATION_LOGO_ID)^
create index IDX_ITPEARLS_APPLICATION_SETUP_ON_APPLICATION_ICON on ITPEARLS_APPLICATION_SETUP (APPLICATION_ICON_ID)^
create index IDX_ITPEARLS_APPLICATION_SETUP_ON_COORDINATOR on ITPEARLS_APPLICATION_SETUP (COORDINATOR_ID)^
create index IDX_ITPEARLS_APPLICATION_SETUP_ON_ADMINISTRATOR on ITPEARLS_APPLICATION_SETUP (ADMINISTRATOR_ID)^
-- end ITPEARLS_APPLICATION_SETUP
