-- Soft-delete test records created by integration tests.
-- Run after: ./gradlew :app-core:test
-- psql -h localhost -U cuba -d HuntTech -f scripts/cleanup-test-entities.sql

UPDATE HUNTTECH_OPEN_POSITION_COMMENT
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE COMMENT_ LIKE 'Test comment %'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_OPEN_POSITION_NEWS
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE SUBJECT LIKE 'TestNews-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_RECRUTIES_TASKS
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE DELETE_TS IS NULL
  AND OPEN_POSITION_ID IN (
      SELECT ID FROM HUNTTECH_OPEN_POSITION WHERE VACANSY_NAME LIKE 'TestVacancy-%' AND DELETE_TS IS NULL
  );

UPDATE HUNTTECH_OPEN_POSITION
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE VACANSY_NAME LIKE 'TestVacancy-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_SKILL_TREE
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE SKILL_NAME LIKE 'TestSkill-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_POSITION
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE POSITION_RU_NAME LIKE 'TestPositionRu-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_GRADE
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE GRADE_NAME LIKE 'TestGrade-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_PROJECT
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE PROJECT_NAME LIKE 'TestProject-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_COMPANY_DEPARTAMENT
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE DEPARTAMENT_RU_NAME LIKE 'TestDept-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_COMPANY
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE COMANY_NAME LIKE 'TestCompany-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_REGION
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE REGION_RU_NAME LIKE 'TestRegion-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_COUNTRY
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE COUNTRY_RU_NAME LIKE 'TestCountry-%'
  AND DELETE_TS IS NULL;

UPDATE HUNTTECH_CITY
SET DELETE_TS = NOW(), DELETED_BY = 'test-cleanup'
WHERE CITY_RU_NAME LIKE 'TestCity-%'
  AND DELETE_TS IS NULL;
