alter table ITPEARLS_COMPANY add constraint FK_ITPEARLS_COMPANY_ON_FILE_COMPANY_LOGO foreign key (FILE_COMPANY_LOGO) references SYS_FILE(ID);
create index IDX_ITPEARLS_COMPANY_ON_FILE_COMPANY_LOGO on ITPEARLS_COMPANY (FILE_COMPANY_LOGO);
