alter table HUNTTECH_PERSON add constraint FK_HUNTTECH_PERSON_ON_FILE_IMAGE_FACE foreign key (FILE_IMAGE_FACE) references SYS_FILE(ID);
create index IDX_HUNTTECH_PERSON_ON_FILE_IMAGE_FACE on HUNTTECH_PERSON (FILE_IMAGE_FACE);
