alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_FILE_IMAGE_FACE foreign key (FILE_IMAGE_FACE) references SYS_FILE(ID);
create index IDX_ITPEARLS_PERSON_ON_FILE_IMAGE_FACE on ITPEARLS_PERSON (FILE_IMAGE_FACE);
