alter table HUNTTECH_PERSON add constraint FK_HUNTTECH_PERSON_ON_CITY_OF_RESIDENCE foreign key (CITY_OF_RESIDENCE_ID) references HUNTTECH_CITY(ID);
create index IDX_HUNTTECH_PERSON_ON_CITY_OF_RESIDENCE on HUNTTECH_PERSON (CITY_OF_RESIDENCE_ID);
