alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_CITY_OF_RESIDENCE foreign key (CITY_OF_RESIDENCE_ID) references ITPEARLS_CITY(ID);
create index IDX_ITPEARLS_PERSON_ON_CITY_OF_RESIDENCE on ITPEARLS_PERSON (CITY_OF_RESIDENCE_ID);
