alter table HUNTTECH_CITY add constraint FK_HUNTTECH_CITY_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references HUNTTECH_CITY(ID);
create index IDX_HUNTTECH_CITY_ON_OPEN_POSITION on HUNTTECH_CITY (OPEN_POSITION_ID);
