alter table ITPEARLS_CITY add constraint FK_ITPEARLS_CITY_ON_OPEN_POSITION foreign key (OPEN_POSITION_ID) references ITPEARLS_CITY(ID);
create index IDX_ITPEARLS_CITY_ON_OPEN_POSITION on ITPEARLS_CITY (OPEN_POSITION_ID);
