alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID);
create index IDX_ITPEARLS_CANDIDATE_CV_ON_OWNER on ITPEARLS_CANDIDATE_CV (OWNER_ID);
