alter table HUNTTECH_SETUP add constraint FK_HUNTTECH_SETUP_ON_PARAM_USER foreign key (PARAM_USER_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_SETUP_ON_PARAM_USER on HUNTTECH_SETUP (PARAM_USER_ID);
