alter table HUNTTECH_CANDIDATE_CV add constraint FK_HUNTTECH_CANDIDATE_CV_ON_SOME_FILES foreign key (SOME_FILES_ID) references HUNTTECH_SOME_FILES(ID);
create index IDX_HUNTTECH_CANDIDATE_CV_ON_SOME_FILES on HUNTTECH_CANDIDATE_CV (SOME_FILES_ID);
