alter table HUNTTECH_RECRUTIES_TASKS add constraint FK_HUNTTECH_RECRUTIES_TASKS_ON_REACRUTIER foreign key (REACRUTIER_ID) references SEC_USER(ID);
create index IDX_HUNTTECH_RECRUTIES_TASKS_ON_REACRUTIER on HUNTTECH_RECRUTIES_TASKS (REACRUTIER_ID);
