alter table HUNTTECH_SOME_FILES rename column candidate_cv_id to candidate_cv_id__u94481 ;
alter table HUNTTECH_SOME_FILES drop constraint FK_HUNTTECH_SOME_FILES_ON_CANDIDATE_CV ;
drop index IDX_HUNTTECH_SOME_FILES_ON_CANDIDATE_CV ;
