alter table HUNTTECH_SOME_FILES add constraint FK_HUNTTECH_SOME_FILES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
alter table HUNTTECH_SOME_FILES add constraint FK_HUNTTECH_SOME_FILES_ON_FILE_OWNER foreign key (FILE_OWNER_ID) references SEC_USER(ID);
alter table HUNTTECH_SOME_FILES add constraint FK_HUNTTECH_SOME_FILES_ON_FILE_TYPE foreign key (FILE_TYPE_ID) references HUNTTECH_FILE_TYPE(ID);
create index IDX_HUNTTECH_SOME_FILES_ON_FILE_DESCRIPTOR on HUNTTECH_SOME_FILES (FILE_DESCRIPTOR_ID);
create index IDX_HUNTTECH_SOME_FILES_ON_FILE_OWNER on HUNTTECH_SOME_FILES (FILE_OWNER_ID);
create index IDX_HUNTTECH_SOME_FILES_ON_FILE_TYPE on HUNTTECH_SOME_FILES (FILE_TYPE_ID);
