alter table ITPEARLS_RECRUTIES_TASKS add constraint FK_ITPEARLS_RECRUTIES_TASKS_ON_REACRUTIER foreign key (REACRUTIER_ID) references SEC_USER(ID);
create index IDX_ITPEARLS_RECRUTIES_TASKS_ON_REACRUTIER on ITPEARLS_RECRUTIES_TASKS (REACRUTIER_ID);
