alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_SOME_FILES foreign key (SOME_FILES_ID) references ITPEARLS_SOME_FILES(ID);
create index IDX_ITPEARLS_CANDIDATE_CV_ON_SOME_FILES on ITPEARLS_CANDIDATE_CV (SOME_FILES_ID);
