cuba.schedulingActive=true
cuba.dataSource.url=jdbc:postgresql://localhost:5432/hunttech
cuba.dataSource.username=cuba
cuba.dataSource.password=cuba
cuba.email.fromAddress=a.ananyev@hunttech.ru
cuba.email.smtpHost=smtp.mail.ru
cuba.email.smtpPort=465
cuba.email.smtpUser=a.ananyev@hunttech.ru
cuba.email.smtpPassword=NSEc9j2jnqi84LYCPPVL
cuba.email.smtpAuthRequired=true
cuba.email.smtpSslEnabled=true
cuba.email.smtpStarttlsEnable=true
cuba.queryCache.enabled=true
cuba.queryCache.maxSize=200
cuba.connectionUrlList=http://localhost:8080/hrm-core
eclipselink.cache.shared.hunttech_OpenPosition=true
eclipselink.cache.size.hunttech_OpenPosition=100
eclipselink.cache.shared.hunttech_IteractionEdit=true
eclipselink.cache.size.hunttech_IteractionEdit=100
eclipselink.cache.shared.hunttech_JobCandidate=true
eclipselink.cache.size.hunttech_JobCandidate=100
eclipselink.cache.shared.hunttech_CandidateCV=true
eclipselink.cache.size.hunttech_CandidateCV=100
eclipselink.cache.shared.hunttech_Company=true
eclipselink.cache.size.hunttech_Company=100
eclipselink.cache.shared.hunttech_Project=true
eclipselink.cache.size.hunttech_Project=100
eclipselink.cache.shared.hunttech_CompanyDepartament=true
eclipselink.cache.size.hunttech_CompanyDepartament=100
eclipselink.cache.shared.hunttech_CompanyGroup=true
eclipselink.cache.size.hunttech_CompanyGroup=100
eclipselink.cache.shared.hunttech_Country=true
eclipselink.cache.size.hunttech_Country=100
eclipselink.cache.shared.hunttech_Iteraction=true
eclipselink.cache.size.hunttech_Iteraction=100
eclipselink.cache.shared.hunttech_Position=true
eclipselink.cache.size.hunttech_Position=100
