/*
 * HuntTech HRM data migration from legacy PostgreSQL database `itpearls`.
 *
 * Run this script inside the NEW target database `hunttech`.
 *
 * Data policy:
 * - Source data is never modified.
 * - UUIDs, dates, relations and CUBA system table rows are copied as-is.
 * - Only custom table name prefixes are mapped: itpearls_* -> hunttech_*.
 *
 * Preconditions:
 * - Target schema public already contains HuntTech tables generated by CUBA.
 * - Target database may be freshly initialized by CUBA createDb; mapped target
 *   tables are truncated before copying so generated starter rows do not mix
 *   with production data.
 * - The executing database role has enough rights to:
 *   CREATE EXTENSION, CREATE SERVER, CREATE USER MAPPING,
 *   IMPORT FOREIGN SCHEMA, and SET session_replication_role.
 *
 * Adjust the user/password options below if the local PostgreSQL credentials
 * differ from the default CUBA development credentials.
 */

BEGIN;

CREATE EXTENSION IF NOT EXISTS dblink;
CREATE EXTENSION IF NOT EXISTS postgres_fdw;

DROP SCHEMA IF EXISTS old_itpearls_schema CASCADE;
DROP SERVER IF EXISTS old_itpearls_server CASCADE;

CREATE SERVER old_itpearls_server
    FOREIGN DATA WRAPPER postgres_fdw
    OPTIONS (
        host '127.0.0.1',
        port '5432',
        dbname 'itpearls'
    );

CREATE USER MAPPING FOR CURRENT_USER
    SERVER old_itpearls_server
    OPTIONS (
        user 'cuba',
        password 'cuba'
    );

DO $$
BEGIN
    PERFORM dblink_connect(
        'old_itpearls_check',
        'host=127.0.0.1 port=5432 dbname=itpearls user=cuba password=cuba'
    );
    PERFORM dblink_disconnect('old_itpearls_check');
END;
$$;

CREATE SCHEMA old_itpearls_schema;

IMPORT FOREIGN SCHEMA public
    FROM SERVER old_itpearls_server
    INTO old_itpearls_schema;

CREATE TEMP TABLE migration_table_map (
    copy_group text NOT NULL,
    source_table text NOT NULL,
    target_table text NOT NULL,
    PRIMARY KEY (source_table, target_table)
) ON COMMIT DROP;

/*
 * Required CUBA system tables. They keep their names.
 */
INSERT INTO migration_table_map (copy_group, source_table, target_table)
VALUES
    ('system', 'sec_user', 'sec_user'),
    ('system', 'sec_role', 'sec_role'),
    ('system', 'sec_group', 'sec_group'),
    ('system', 'sys_file', 'sys_file')
ON CONFLICT DO NOTHING;

/*
 * Copy all same-name non-application tables that exist in both databases:
 * CUBA internals, add-ons, reports, BPM/Activiti, email templates, etc.
 */
INSERT INTO migration_table_map (copy_group, source_table, target_table)
SELECT CASE
           WHEN ft.foreign_table_name LIKE 'sec\_%' ESCAPE '\'
             OR ft.foreign_table_name LIKE 'sys\_%' ESCAPE '\'
               THEN 'system'
           ELSE 'shared'
       END AS copy_group,
       ft.foreign_table_name,
       ft.foreign_table_name
FROM information_schema.foreign_tables ft
JOIN information_schema.tables tt
    ON tt.table_schema = 'public'
   AND tt.table_name = ft.foreign_table_name
WHERE ft.foreign_table_schema = 'old_itpearls_schema'
  AND ft.foreign_table_name NOT LIKE 'itpearls\_%' ESCAPE '\'
  AND ft.foreign_table_name NOT LIKE 'hunttech\_%' ESCAPE '\'
ON CONFLICT DO NOTHING;

/*
 * Custom application tables. Examples explicitly required for audit:
 * - old_itpearls_schema.itpearls_user_settings -> public.hunttech_user_settings
 * - old_itpearls_schema.itpearls_user_ai_configuration -> public.hunttech_user_ai_configuration
 */
INSERT INTO migration_table_map (copy_group, source_table, target_table)
SELECT 'custom',
       ft.foreign_table_name,
       regexp_replace(ft.foreign_table_name, '^itpearls_', 'hunttech_') AS target_table
FROM information_schema.foreign_tables ft
JOIN information_schema.tables tt
    ON tt.table_schema = 'public'
   AND tt.table_name = regexp_replace(ft.foreign_table_name, '^itpearls_', 'hunttech_')
WHERE ft.foreign_table_schema = 'old_itpearls_schema'
  AND ft.foreign_table_name LIKE 'itpearls\_%' ESCAPE '\'
ON CONFLICT DO NOTHING;

SET session_replication_role = 'replica';

DO $$
DECLARE
    truncate_list text;
BEGIN
    SELECT string_agg(format('public.%I', target_table), ', ')
    INTO truncate_list
    FROM migration_table_map;

    IF truncate_list IS NULL THEN
        RAISE EXCEPTION 'No matching tables found for migration.';
    END IF;

    EXECUTE 'TRUNCATE TABLE ' || truncate_list || ' RESTART IDENTITY CASCADE';
END;
$$;

DO $$
DECLARE
    r record;
    inserted_rows bigint;
    target_columns text;
    source_expressions text;
    missing_columns text;
BEGIN
    FOR r IN
        SELECT copy_group, source_table, target_table
        FROM migration_table_map
        ORDER BY copy_group, target_table
    LOOP
        WITH target_cols AS (
            SELECT ordinal_position, column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = r.target_table
        ),
        source_cols AS (
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'old_itpearls_schema'
              AND table_name = r.source_table
        ),
        mapped_cols AS (
            SELECT tc.ordinal_position,
                   tc.column_name AS target_column,
                   COALESCE(sc_exact.column_name, sc_legacy.column_name) AS source_column
            FROM target_cols tc
            LEFT JOIN source_cols sc_exact
                ON sc_exact.column_name = tc.column_name
            LEFT JOIN source_cols sc_legacy
                ON sc_legacy.column_name = replace(tc.column_name, 'hunttech', 'itpearls')
        )
        SELECT string_agg(format('%I', target_column), ', ' ORDER BY ordinal_position),
               string_agg(format('%I', source_column), ', ' ORDER BY ordinal_position),
               string_agg(target_column, ', ' ORDER BY ordinal_position)
                   FILTER (WHERE source_column IS NULL)
        INTO target_columns, source_expressions, missing_columns
        FROM mapped_cols;

        IF missing_columns IS NOT NULL THEN
            RAISE EXCEPTION
                'Cannot copy old_itpearls_schema.% -> public.%: missing compatible source columns for target columns: %',
                r.source_table,
                r.target_table,
                missing_columns;
        END IF;

        EXECUTE format(
            'INSERT INTO public.%I (%s) SELECT %s FROM old_itpearls_schema.%I',
            r.target_table,
            target_columns,
            source_expressions,
            r.source_table
        );

        GET DIAGNOSTICS inserted_rows = ROW_COUNT;
        RAISE NOTICE 'Copied % rows: old_itpearls_schema.% -> public.%',
            inserted_rows,
            r.source_table,
            r.target_table;
    END LOOP;
END;
$$;

SET session_replication_role = 'origin';

DROP SCHEMA old_itpearls_schema CASCADE;
DROP SERVER old_itpearls_server CASCADE;

COMMIT;
