alter table ITPEARLS_APPLICATION_SETUP drop column TELEGRAM_BOT_STARTED__U76883 cascade ;
alter table ITPEARLS_APPLICATION_SETUP drop column ADMINISTRATOR_ID__U80578 cascade ;
alter table ITPEARLS_APPLICATION_SETUP drop column COORDINATOR_ID__U27801 cascade ;
