alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_PARTNERS foreign key (PARTNERS_ID) references ITPEARLS_COMPANY(ID);
create index IDX_ITPEARLS_PERSON_ON_PARTNERS on ITPEARLS_PERSON (PARTNERS_ID);
