alter table ITPEARLS_CANDIDATE_CV add constraint FK_ITPEARLS_CANDIDATE_CV_ON_PARTNERS foreign key (PARTNERS_ID) references ITPEARLS_COMPANY(ID);
create index IDX_ITPEARLS_CANDIDATE_CV_ON_PARTNERS on ITPEARLS_CANDIDATE_CV (PARTNERS_ID);
