alter table ITPEARLS_PERSON add constraint FK_ITPEARLS_PERSON_ON_PARTNER foreign key (PARTNER_ID) references ITPEARLS_COMPANY(ID);
create index IDX_ITPEARLS_PERSON_ON_PARTNER on ITPEARLS_PERSON (PARTNER_ID);
