alter table ITPEARLS_JOB_CANDIDATE add constraint FK_ITPEARLS_JOB_CANDIDATE_ON_PARTNERS foreign key (PARTNERS_ID) references ITPEARLS_COMPANY(ID);
create index IDX_ITPEARLS_JOB_CANDIDATE_ON_PARTNERS on ITPEARLS_JOB_CANDIDATE (PARTNERS_ID);
