alter table ITPEARLS_ITERACTION_LIST add constraint FK_ITPEARLS_ITERACTION_LIST_ON_PARTNER foreign key (PARTNER_ID) references ITPEARLS_COMPANY(ID);
create index IDX_ITPEARLS_ITERACTION_LIST_ON_PARTNER on ITPEARLS_ITERACTION_LIST (PARTNER_ID);
